### ISSUE TITLE
How to change the default "universal" logo?

### ISSUE THREAD

**Issue by sshesh** [devcows/hugo-universal-theme#105]
I am new to Hugo and using this theme for the first time on my ubuntu 14.04. I am able to view the webpage (upon running hugo server -w) with the template (hugo-universal-theme). However, when I replace the image under /static/img/logo.png with another image but with the same name, I still see the old "Universal" logo on the left top bar. How do I update the logo to reflect my new image? So far I have tried stopping and restarting local server, renaming the file under config.toml but without much success.

Thanks for your help,

**Comment by GeorgeWL** [comment]
replace the file with another of the same in the `static` folder
