### ISSUE TITLE
Consistency of "Recent Posts" Length

### ISSUE THREAD

**Issue by neilchaudhuri** [devcows/hugo-universal-theme#110]
I have enabled `recent_posts`, and I have found that the blurbs revealed beneath the titles are of varying lengths. This leads to an inconsistent look. Is there a way to control how many characters get displayed so the blurbs all look uniform?

Thanks.

**Comment by rjsmith** [comment]
Take a look at https://gohugo.io/content-management/summaries/

I use the `<!--more-->` tag to manually mark where I want the blog summary to stop.
