### ISSUE TITLE
example site /blog doesn't work

### ISSUE THREAD

**Issue by gideondsouza** [devcows/hugo-universal-theme#121]
I first posted this here https://discourse.gohugo.io/t/just-getting-my-site-going-with-a-simple-theme/9105?u=gideondsouza

**Comment by ryanfox1985** [comment]
Hi @gideondsouza,

do you have a public repository to see all the project folder?

Regards.

**Comment by gideondsouza** [comment]
yes. here : https://github.com/gideondsouza/gideondsouza-hugo
However I fiddled with single.html and somehow it now works!

**Comment by GeorgeWL** [comment]
@gideondsouza well if you ever figure out how then let us know so we can mark whether this is a bug, or if it's instead human error 😺
