### ISSUE TITLE
Author wse post list

### ISSUE THREAD

**Issue by webuimaker** [devcows/hugo-universal-theme#123]
Hi,
I need help for how to show Author Wise post list after click on Author name like Categories post list.

Thanks

**Comment by GeorgeWL** [comment]
This is found in the hugo docs 😃 

The option is changing a little bit of the code.

**Comment by webuimaker** [comment]
I tried 
{{ if isset .Params "authors" }}
													{{ i18n "authorBy" }} <a href="{{ $.Site.BaseURL }}author/{{ index .Params.author 0 | urlize | lower  }}">{{ .Params.author }}</a>
												{{ end }}

and for list 


{{ range $name, $items := .Site.Params.authors }}
                {{ range $key, $val := $items }}
				{{ $key }}
                    {{ if eq $key "name" }}


                        <li>
                        <a href="{{ $.Site.BaseURL }}authors/{{ $val | urlize | lower }}"><i class="fa fa-user"></i> {{ $val }}

                        ({{ len (where $.Site.Pages ".Params.authors" $name) }})  ({{ len $items }})
                        </a>
                        </li>



                    {{ end }}
                {{ end }}
            {{ end }}
