### ISSUE TITLE
why define logo?

### ISSUE THREAD

**Issue by r2evans** [devcows/hugo-universal-theme#126]
If I define a filename other than `img/logo.png` as the logo, it isn't used because the `layouts/partials/nav.html` includes the hard-coded path and filename for both `img/logo.png` and `img/logo-small.png`. Is it a problem of a magic constant defined in `nav.html` or my misinterpretation of documentation?

**Comment by alexislg2** [comment]
+1 

It can be a problem if you want to work with .svg file

**Comment by dtoubelis** [comment]
+1

**Comment by YaguraStation** [comment]
We put `logo-small.png` and `logo.png` into `static/img`. Working fine so far.

**Comment by r2evans** [comment]
@YaguraStation, how is that helpful here? That works because they are the hard-coded path/filenames, as I said. Did you try what I suggested as the problem, defining a logo with a different filename?

**Comment by YaguraStation** [comment]
@r2evans Helpful because one doesn't need to touch anything in the theme by instead using one owns `static` directory. Also beneficial in staying up-to-date with the upstream theme more easily.

**Comment by dtoubelis** [comment]
It i9s either need to be removed from configuration or properly used in templates. Right now it is a mess.

**Comment by r2evans** [comment]
@YaguraStation, you're missing the point. What if I need to use (as alexislg2 commented) something other than PNG?

Magic constants have their place, perhaps. I'm suggesting that there is enough utility here to make this *not* magic, allowing us to define the logo path and filename.

How does using the hard-coded  `img/logo.png` help stay up-to-date with upstream? How would allowing a user-defined logo path not support staying up-to-date?

**Comment by YaguraStation** [comment]
@r2evans I was suggesting a temp fix / workaround that has proven itself. Regarding upstream parity: Using static in the meanwhile will prevent making changes and fixes now that might be difficult to reconcile later on.  

If you've fixed this already, please submit a PR.

**Comment by r2evans** [comment]
@YaguraStation, what you suggested is not a temp-fix for uses where the logo is not PNG. There is no temp-fix other than to fix `layouts/partials/nav.html` where they [hard-code `img/logo.png`](https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/nav.html#L8-L9). This should not be news to the devs, as it is done correctly in both `layouts/partial/nav.html` to match both [`layouts/404.html`](https://github.com/devcows/hugo-universal-theme/blob/master/layouts/404.html#L25) and [`layouts/partials/head.html`](https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/head.html#L65), where they correctly use `.Site.Params.logo`.

**Comment by GeorgeWL** [comment]
Feel free to pull request @r2evans, the more helpers the better this theme can be

**Comment by r2evans** [comment]
@GeorgeWL, is it really as simple as:

```diff
--- nav.html.orig       2018-06-06 15:52:04.053135700 -0700
+++ nav.html    2018-06-06 15:52:41.116596600 -0700
@@ -5,7 +5,7 @@
         <div class="container">
             <div class="navbar-header">
                 <a class="navbar-brand home" href="{{ .Site.BaseURL }}">
-                    <img src="{{ .Site.BaseURL }}img/logo.png" alt="{{ .Title }} logo" class="hidden-xs hidden-sm">
-                    <img src="{{ .Site.BaseURL }}img/logo-small.png" alt="{{ .Title }} logo" class="visible-xs visible-sm">
+                    <img src="{{ .Site.BaseURL }}{{ .Site.Params.logo }}" alt="{{ .Title }} logo" class="hidden-xs hidden-sm">
+                    <img src="{{ .Site.BaseURL }}{{ .Site.Params.logo_small }}" alt="{{ .Title }} logo" class="visible-xs visible-sm">
                     <span class="sr-only">{{ .Title }} - {{ i18n "navHome" }}</span>
                 </a>
```

plus a new `config.toml` entry for `logo_small`?

**Comment by GeorgeWL** [comment]
I think you're right yeah. 

We were considering at one point to see about just getting the api for https://realfavicongenerator.net/ into it, but it felt like a lot of effort. #77 

```toml
# something like this
 [params.favicon]
  # you may want to use https://realfavicongenerator.net to generate you files
  # used in layouts/partials/head.favicon.html
  # relURL is applied to path 
  enable    = true
  path      = "/images/favicons"
  version   = "a_random_value"
  maskIicon = "#5bbad5" 
  tileColor = "#da532c" 
  themeColor= "#ffffff"
```
combined with this favicons partial
```html
<link rel="apple-touch-icon"      sizes="180x180" href="{{ relURL "/images/favicons/apple-touch-icon.png"       }}" />
<link rel="icon" type="image/png" sizes="32x32"   href="{{ relURL "/images/favicons/favicon-32x32.png"          }}" />
<link rel="icon" type="image/png" sizes="192x192" href="{{ relURL "/images/favicons/android-chrome-192x192.png" }}" />
<link rel="icon" type="image/png" sizes="16x16"   href="{{ relURL "/images/favicons/favicon-16x16.png"          }}" />
<link rel="manifest"                              href="{{ relURL "/images/favicons/manifest.json"              }}" />
<link rel="mask-icon"  color="#5bbad5"            href="{{ relURL "/images/favicons/safari-pinned-tab.svg"      }}" />
<link rel="shortcut icon"                         href="{{ relURL "/images/favicons/favicon.ico"                }}" />
<meta name="msapplication-TileImage"           content="{{ relURL "/images/favicons/mstile-144x144.png"         }}" />
<meta name="msapplication-config"              content="{{ relURL "/images/favicons/browserconfig.xml"          }}" />
<meta name="msapplication-TileColor" content="#da532c" />
<meta name="theme-color"             content="#ffffff" />
```

**Comment by GeorgeWL** [comment]
@dtoubelis it's detailed in #77 , basically, for most purposes you only really need a single favicon, but there's so many edge cases, like "What if they decided to add the bookmark to their start bar on windows 7/8/10?" or "Will my favicon look weird after Safari converts it into a monochrome silhouette?" or "What if they decide to add the website as a bookmark on Android Home Screen, cause that automatically wraps it in a little white circle unless you override the icon and color" that adding extra options makes sense if you wanna make sure it works in all cases.

**Comment by dtoubelis** [comment]
@GeorgeWL I'm failing to see any relationship between favicons and the logo, so your favicon related comments do not contribute to this topic.

**Comment by GeorgeWL** [comment]
confusing related things ha, don't worry, will remove my related thing.

**Comment by ryanfox1985** [comment]
I close the issue as resolvedby the PR.
