### ISSUE TITLE
Make FontAwesome clickable

### ISSUE THREAD

**Issue by samuel-rosa** [devcows/hugo-universal-theme#127]
Is it possible to add a link to icons in Features and make FontAwesome icons clickable?

**Comment by samuel-rosa** [comment]
This is my current solution:
1. Inside folder `layouts`, create a folder `partials`;
2. In the previous folder, make a copy of file `features.html` from `/themes/hugo-universal-theme/layouts/partials`;
3. Find the following code (line 13 - 15):
```
<div class="icon">
  <i class="{{ .icon }}"></i>
</div>
```
4. In line 14, add the following code:
```
<a href="{{ .url }}">
```
5. In the YAML front matter of a feature use `url` to pass the website address.

Is there a cleaner, more elegant solution?

**Comment by jcolomb** [comment]
The problem  is that all icons get the function and there is no default page, such that you get error 404 if you do not set url in the YAML.

**Comment by GeorgeWL** [comment]
Just need to add a check to the partial injection then that will go 
**not real code**
```
if(isExternal(url)){
link = url
}
```
with `isExternal(url)` being a regex check for if it starts with `http`/`https`/`www` etc

**Comment by jcolomb** [comment]
Ok got it to work, the problem was that the href tag was not closed and the link was given to all text following. Here is the workaround: modify the feature.html like this (line12-18 to change to):

```
 <div class="box-simple">
                          <div class="icon">
                            <i class="{{ .icon }}"></i>
                            <a href="{{ .url }}"> 
                          </div>
                        <h3>{{ $element.name }}</h3>
                        <p>{{ $element.description | markdownify }}</p>
                        </a>
                    </div>
```

**Comment by GeorgeWL** [comment]
@jcolomb fancy making a pull request for that?

**Comment by jcolomb** [comment]
I do !

**Comment by GeorgeWL** [comment]
go ahead and we'll review it @jcolomb

**Comment by jcolomb** [comment]
see
https://github.com/devcows/hugo-universal-theme/pull/166

**Comment by salim-b** [comment]
> see
> #166

or see [my comment](https://github.com/devcows/hugo-universal-theme/pull/166#issuecomment-421629371) about a (slightly different) approach

**Comment by norcalbiostat** [comment]
bumping this for review - i would really like this to be implemented.

**Comment by ryanfox1985** [comment]
I'm closing this issue because #184 is implementing the feature clicklable.
