### ISSUE TITLE
carousel transition

### ISSUE THREAD

**Issue by samuel-rosa** [devcows/hugo-universal-theme#128]
How can the carousel transition time be set? Is there any parameter for that purpose?

**Comment by ryanfox1985** [comment]
Thanks for the proposal, it can be a good idea. 

You are welcome to contribute this repository.

**Comment by jcolomb** [comment]
It is probably in the css file, isn't it?

**Comment by GeorgeWL** [comment]
not 100% sure, I've forgotten whether it's pure css or if there's some JavaScript that sets that transition period.

Open Source, so feel free to Pull Request and we'll review it and add it to the repo.

**Comment by jcolomb** [comment]
I think this is set in the front.js file under autoplay variables, but which one it is is still a mystery.
I do not know if it would be possible to make it easy to modify ?

**Comment by ryanfox1985** [comment]
> I think this is set in the front.js file under autoplay variables.
> I do not know if it would be possible to make it easy to modify ?
> 
> I added loop: true, and one can change the autoplay value.
> 
> ```
> function sliderHomepage () {
>   if ($('#slider').length) {
>     // var owl = $('#slider')
> 
>     $('#slider').owlCarousel({
>       autoPlay: 3000,
>       loop: true,
>       items: 4,
>       itemsDesktopSmall: [900, 3],
>       itemsTablet: [600, 3],
>       itemsMobile: [500, 2]
>     })
>   }
> }
> ```

as he said you can override the js applying another transition time.
