### ISSUE TITLE
Drop down menu support?

### ISSUE THREAD

**Issue by Riokei** [devcows/hugo-universal-theme#129]
I'm wondering if its possible to add a drop down menu like so: 
![drop-down-navigation-touch-friendly-and-responsive-1](https://user-images.githubusercontent.com/16841390/33529530-13db4088-d840-11e7-8fe5-800ae33f254d.jpg)
Image borrowed from [here](https://osvaldas.info/drop-down-navigation-responsive-and-touch-friendly)
I have a info pages for specific things under one category I'd like to add and a drop down would suit my needs best but I'm not sure how to implement such a thing myself, the link does have a tutorial so maybe someone could tell me where to put the pieces of html on that link?

**Comment by akbennett** [comment]
see: https://gohugo.io/content-management/menus/ 

```
[menu]
[[menu.main]]
    name = "About Us"
    url  = "/about"
    weight = 4
[[menu.main]]
    parent = 'About Us'
    name = "People"
    url  = "/about#People"
```

**Comment by Riokei** [comment]
Thanks!
