### ISSUE TITLE
/blog/ is empty

### ISSUE THREAD

**Issue by Therotak** [devcows/hugo-universal-theme#133]
Hey there,

I am quite new to Hugo, but even with the example site there is not page showing up once I click on the Blog link on the top menu. I see my blog test pages on the recent blogs, but the main /blo/ site remains white.

I think in the testpage there is page missing,

What am I missing?

Thanks!

**Comment by beatwade** [comment]
@Therotak just run hugo in your project root. the hugo command:
![image](https://user-images.githubusercontent.com/6858148/36626827-b82dfaac-1974-11e8-9aeb-d4db0fb074bd.png)

**Comment by ryanfox1985** [comment]
is it fixed?

**Comment by ryanfox1985** [comment]
closed by inactivity.
