### ISSUE TITLE
Where is the Dutch translation?

### ISSUE THREAD

**Issue by tbool** [devcows/hugo-universal-theme#136]
Hi, there is a pull request for adding a Dutch translation ( #107) that was approved, but somehow never got included in the code. Could it still be added?

**Comment by tbool** [comment]
Never mind, just learned from the Hugo-docs (I am just starting with Hugo...) that it is actually very easy to add your own personal translation file in a i18n/ directory right under the root of the website. Works very well.

**Comment by fedelibre** [comment]
#107 was merged 2 days after this post. Someone can close it?
