### ISSUE TITLE
Will the hugo theme be updated?

### ISSUE THREAD

**Issue by fra42** [devcows/hugo-universal-theme#139]
I checked the demo on the creator site (https://demo.bootstrapious.com/universal/2-0/) and I found that his version is more updated than this one. 
Will there be an update of the hugo version soon?

**Comment by salim-b** [comment]
I think this qualifies as a duplicate of #101 

@GeorgeWL / @ryanfox1985 I'd close this issue in favor of #101

**Comment by ryanfox1985** [comment]
I updated recently some small things. I think can be very difficult to adapt the current theme to the version V2 they changed many things.
