### ISSUE TITLE
Use text instead of logo

### ISSUE THREAD

**Issue by ccamara** [devcows/hugo-universal-theme#140]
Default settings define a logo that will be used in all pages. Could it be possible to use a text instead of an image? if so, how?

Thanks

**Comment by ryanfox1985** [comment]
there is no posibility to instead of the logo use text, right now the only thing that you can do is create an image with these text and set here:

https://github.com/salim-b/hugo-universal-theme/blob/e41d8712415a97e89bd667bf3afce75cf79c0a24/exampleSite/config.toml#L110-L111

**Comment by ryanfox1985** [comment]
I attach the label wontfix because I thing is out of the theme scope.
