### ISSUE TITLE
To prevent spam, only Gold accounts may create AJAX forms.

### ISSUE THREAD

**Issue by tovmeod** [devcows/hugo-universal-theme#147]
After configuring formspree I can't send the form, I receive 400 with the following:

{
  "error": "To prevent spam, only Gold accounts may create AJAX forms."
}

**Comment by vittorio88** [comment]
Hello,

I too have this issue.

I have submitted an updated pull-request here: https://github.com/devcows/hugo-universal-theme/pull/203

This works for me, and you can view it here:
https://www.lagobello.com/contact/
