### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [devcows/hugo-universal-theme#150]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following (site main page won't show posts, but single pages render ok):

```
Building sites … ERROR 2018/03/20 19:04:14 Error while rendering "page" in "post/": template: theme/_default/single.html:27:195: executing "theme/_default/single.html" at <.Site.Params.date_fo...>: invalid value; expected string
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
```

The reason is likely some absent `.Site.` parameter but you can't tell it from error message, I guess input parameters handling could be improved. https://github.com/cboettig/hugo-now-ui/issues/9 might be used as reference point.

By they way, `.Site.Params.dateformat` is more commonly used than `.Site.Params.date_format`.

**Comment by paskal** [comment]
https://github.com/hivickylai/hugo-theme-sam/pull/3 is an example of how this can be fixed.

**Comment by mattburns** [comment]
I also got stung by this as a first time user of Hugo. Not obvious that date_format param is mandatory. 
Perhaps it could just be wrapped in null checks like this: `{{ if .Site.Params.date_format}}{{ .Date.Format .Site.Params.date_format }}{{ end }}` ?

**Comment by salim-b** [comment]
> Perhaps it could just be wrapped in null checks like this: `{{ if .Site.Params.date_format}}{{ .Date.Format .Site.Params.date_format }}{{ end }}` ?

Nowadays, the recommended way is to just use [`with`](https://gohugo.io/functions/with) which automatically skips the block if the variable is absent.

**Comment by paskal** [comment]
Default state [like this](https://github.com/vickylai/hugo-theme-sam/blob/f332383682dd632e6179c70709a70d5c0a0d2193/layouts/_default/list.html#L4) will do the job. I can create a PR but I have many more PRs hanging without merge than actually merged, and want to developer to confirm he is willing to get one before doing it.
