### ISSUE TITLE
Suggestion change background image at Carousel and make it possible to place a link

### ISSUE THREAD

**Issue by ohobby** [devcows/hugo-universal-theme#157]
Hi,

my Suggestion is to make it possible to change the background image at Carousel with the slide and make it possible to place a link.

Thanks,
Oliver

**Comment by andresalerno** [comment]
Good one. I'm following this suggestion ;)

**Comment by jules32** [comment]
Hi, 

Thank you so much for the hugo-universal-theme, I am using it and really appreciative. 

I wanted to follow up on this thread – is it possible to change the background image in the Carousel? I was hoping that as the carousel cycles through and the words change, I can have the background image change as well. 

Thank you!

**Comment by GeorgeWL** [comment]
@jules32 yeah it's possible, it's html and CSS at its core, if it's possible to do in html and CSS, then it's possible in this theme.

**Comment by jules32** [comment]
Thanks! I will need to ask others for help, but if we make it happen I'll post back here.

**Comment by ryanfox1985** [comment]
Hello there,

the background image is possible to change via CSS, overriding the background image for this class `.home-carousel` and the link is done in this PR: https://github.com/devcows/hugo-universal-theme/pull/343

Regards.

**Comment by diapason-consulting** [comment]
Hey there. Hope it is ok to hijack this thread.
I'm trying to do something even simpler: how can I just change the background image without it being dynamic?
