### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by alexislg2** [devcows/hugo-universal-theme#159]
Hello,
the font size in this theme is 14px, which is considered too small by Google for best SEO result.
![image](https://user-images.githubusercontent.com/7933080/39779475-92574a80-5309-11e8-9a10-79b5e01b2a21.png)

**Comment by GeorgeWL** [comment]
Should be a quick fix, why not have a go at creating a pull request for it @alexislg2 ?

**Comment by GeorgeWL** [comment]
@lgallen I'd usually agree,  but the SEO result is usually a good guideline to follow, so it might make sense to make this change anyway.

**Comment by ryanfox1985** [comment]
> Although I agree the font looks too small to me, I'm not sure if this should be changed in the theme. However, it is as simple as adding this to your custom.css file.
> 
> ```
> #post-content {
>   font-size: 18px;
> }
> ```

as he said you can override the styles, we cannot modify the theme style by default.
