### ISSUE TITLE
How could I change Fontawesome in the landing page

### ISSUE THREAD

**Issue by andresalerno** [devcows/hugo-universal-theme#161]
Hi!

I've have been trying change some fontawesome icons in the home page, but I could not solve this issue. Someone could help me?

At this moment, I'm using the theme in the Linux plataform and I have not uploaded yet....

Tks,

**Comment by GeorgeWL** [comment]
https://github.com/devcows/hugo-universal-theme/tree/master/exampleSite/data/features

has an example.

You also have the option to completely remove the Features Partial by editing the https://github.com/devcows/hugo-universal-theme/blob/master/layouts/index.html to no longer contain the line `{{ partial "features.html" . }}`

**Comment by GeorgeWL** [comment]
closing this, if you're still having issue @andresalerno lemme know by commenting here and we'll re-open.

**Comment by andresalerno** [comment]
Tks @GeorgeWL! I got it! The issue has changed ;) When I trying to pointing for another icon address in the FontAwesome website, some of them work it. But another one, does not working. Is that possible that I might update the FontAwesome embedded in hugo's template? Best!

**Comment by GeorgeWL** [comment]
Yeah course you can, it's just plain old html pulled in from https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/head.html#L26.


@andresalerno 
If you fancy it, fork this, make changes, then make a pull request to update the font-awesome used for everyone else too.

I think this is a rather old version at this point, 4.7.0 at latest, they've just released 5.0.13 quite recently and it's a major overhaul of the way it works and has a lotta lotta more icons.

**Comment by andresalerno** [comment]
Tks again for your support @GeorgeWL ;) As a matter of fact this is my first incursion in the GitHub platform, so I was little afraid to follow your suggestion about change this issue, but I have already tried. There is my first pull request here ;)
Best my friend!
