### ISSUE TITLE
Is there possible using files .Rmd in the Blog's content?

### ISSUE THREAD

**Issue by andresalerno** [devcows/hugo-universal-theme#163]
Hi!

I'm little stuck with this issue......I decided not using blogdown package in RStudio because of performance problems (I don't know why. I have already installed RStudio n-times!).

Thus, I've completed the whole installation using Ubuntu (Virtual Machine hosted by W10) and inside the blog contents I have some .md and .Rmd files. I don't know why my .Rmd files aren't rendering when I'm using hugo server comands.

Any hint?

Tks!

**Comment by GeorgeWL** [comment]
This is more a https://github.com/gohugoio/hugo issue really, the theme only handles skinning, not the rendering of content.
