### ISSUE TITLE
renaming blog folder to post

### ISSUE THREAD

**Issue by jcolomb** [devcows/hugo-universal-theme#164]
I am using Rblogdown which create new blog post in a folder named "post", I could not find where to tell the template to look for content there instead of the blog folder. any thought?

**Comment by GeorgeWL** [comment]
https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/recent_posts.html#L19

**Comment by jcolomb** [comment]
thanks but what about the blog page? 

that one does the trick for the blog preview on the homepage, not the blog page.

**Comment by GeorgeWL** [comment]
it's a Hugo thing, not our theme, so here's the docs: https://gohugo.io/getting-started/directory-structure/

the theme only handles skinning really, no logic or structure.

**Comment by jcolomb** [comment]
from what I read, post should work too...

Got a workaround in  Rblogdown (https://bookdown.org/yihui/blogdown/global-options.html)

**Comment by GeorgeWL** [comment]
basically, you have to go through replacing all references to blog with post in the theme.

Or create a new directory with new templates in it especially for the new section.
