### ISSUE TITLE
Logo does not appear in mobile plataform

### ISSUE THREAD

**Issue by andresalerno** [devcows/hugo-universal-theme#169]
Hi!

I do not know why the logo appears in the web browser without any problems, but when I do access in mobile plataform appears the "Universal Logo".

How could I solve this issue?

Best,

**Comment by GeorgeWL** [comment]
use https://realfavicongenerator.net to generate the icons required for mobile.

It depends on the mobile OS and the mobile Browser used, many will just try to auto-shrink the default favicon, but some will look for icons-small, and if they can't find that, a manifest.xml and if they can't find it, will default to the first letter of the site title.

We've been talking about replacing the current partial with one generated by realfavicongenerator, but it never really got past planning.

**Comment by GeorgeWL** [comment]
@andresalerno if you wanna make a PR which replaces the partial with one that uses the code generated by that, then please do. closing this issue for now.
