### ISSUE TITLE
How can I disable the map in the contact page?

### ISSUE THREAD

**Issue by whgandalf** [devcows/hugo-universal-theme#170]
I removed the value of every variable related with google maps, but the map is not disabled, I still see a blue box with an error from google maps, is it a feature of the theme or should I just override the contact html template?

**Comment by whgandalf** [comment]
Oh, ok, it is different then to have it empty than having them undefined, I mean, I had this:

```
# Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""
    latitude = ""
    longitude = ""
    direction = ""
```
But it was not working, so commenting all is the solution, thanks for your input @GeorgeWL

```
# Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = ""
    #latitude = ""
    #longitude = ""
    #direction = ""
```

**Comment by GeorgeWL** [comment]
I think also removing the lines entirely does the same.

But you have made us aware of a bug, it shouldn't read empty strings as a value really.

I'll close this and make a new bug report that it reads empty strings as values.
