### ISSUE TITLE
Adding new pages - template

### ISSUE THREAD

**Issue by imransshah** [devcows/hugo-universal-theme#171]
Is there a template for a 'Meet the Team' type of page?

**Comment by GeorgeWL** [comment]
nope.

You could make one if you like. But we aren't going to add one ourselves.

Read the Hugo docs for details on adding your own extra templates. 

I propose that if you want a quick solution, modifying the https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/clients.html template or the https://github.com/devcows/hugo-universal-theme/blob/master/layouts/partials/contact.html would be quickest.

**Comment by imransshah** [comment]
Thank you George - appreciate the help.

---

Thanks,
Imran Shah
301 538 6708 (C)
imran@shah.org

LinkedIn: imransshah

"Make your actions in private better than your actions in public - this is
ikhlaas (sincerity)."

**Comment by imransshah** [comment]
Thank you for the resources – hopefully this will work!

 

-- 

Thanks,

Imran Shah
301 538 6708 (C)
imran@shah.org  <mailto:imran@shah.org>     |     LinkedIn: imransshah

"Service to others is the rent that you pay for your room here on Earth." – The Greatest
