### ISSUE TITLE
add a twitter card

### ISSUE THREAD

**Issue by jcolomb** [devcows/hugo-universal-theme#179]
When sharing website on twitter, it looks for a twitter card to get an image (and do not get any at the moment).

I think this could be done by modifying head.html, look at https://stackoverflow.com/questions/45915720/relative-image-paths-for-twitter-cards-in-blogdown

it will need a complete url for the image, can it be bought using {{.site}} ?

I do not feel very confident in doing it myself, yet...

**Comment by ryanfox1985** [comment]
merged
