### ISSUE TITLE
Unable to apply theme using Config file

### ISSUE THREAD

**Issue by speech1stclinic** [devcows/hugo-universal-theme#187]
Hi Team,

I am using the uploaded config file and facing some error and unable to apply theme.
Can anyone please test if there is any issue with config file and help rectify this.

I have created Theme folder inside the site/abc.com folder and followed all steps.
I am skeptic about using below elements
theme = "hugo-universal-theme"
themesDir = "../.."

//
Building sites . ERROR 2018/09/30 22:24:03 Error while rendering "home" in "": t
emplate: index.html:18:11: executing "index.html" at <partial "carousel.ht...>:
error calling partial: template: partials/carousel.html:3:10: executing "partial
s/carousel.html" at <len .Site.Data.carou...>: error calling len: len of untyped
 nil
Total in 165 ms
Error: Error building site: logged 1 error(s)
///

Thanks

**Comment by GeorgeWL** [comment]
I think you may have enabled carousel then gave it content,

Tbh though we should have built in a fail-safe for that.

**Comment by ryanfox1985** [comment]
same issue #328 mitigation => https://github.com/devcows/hugo-universal-theme/issues/328#issuecomment-933173823
