### ISSUE TITLE
Carousel not displaying in local mode

### ISSUE THREAD

**Issue by ngehani** [devcows/hugo-universal-theme#19]
I have cloned the repo https://gaia-docker.github.io/tugbot-site/ locally and it runs fine. The only thing that doesn't show up on localhost:1313/tugbot-site is the Carousel. Any ideas? on the above link it does.

**Comment by adrianmo** [comment]
@ngehani Thank you for reporting the issue. One of the latest PR that I merged today broke the carousel...

Please update your site with the latest code and you should now be fine :)

Best,
Adrian

**Comment by ngehani** [comment]
Thanks! That worked
