### ISSUE TITLE
I can make the images auto resize?

### ISSUE THREAD

**Issue by svcuonghvktqs** [devcows/hugo-universal-theme#196]
Hello,

I'm building a website using your theme but the image doesn't get smaller when the window is resized in the Blog. 

![1](https://user-images.githubusercontent.com/31816408/48312411-ff071000-e5be-11e8-8362-732c526c2476.PNG)

How to have the images automatically resize in dimension just like with text?

Thank you,

**Comment by GeorgeWL** [comment]
Add some css to the image.
