### ISSUE TITLE
New page looks like new post

### ISSUE THREAD

**Issue by MislavSag** [devcows/hugo-universal-theme#200]
I made new folder inside content folder (lets say 'newFolder'), and also made new markdown file inside 'newFolder' folder. I just copied some text from other markdown files to my new md file.
So, in the end, there should be new page which can be clicked from drop down menu: newFolder > md file.

I can see my new page, but the problem is that my new page looks like a post and not like 'faq' or 'contact' page.

How can I make new page, inside folder, which is not like a post page (doesn't have tags, search etc)?

**Comment by MislavSag** [comment]
Ok, I get it. If I create md file inside content folder it is "ordinary page", but if I create it inside folder inside content folder, then it is a post?

I remove all files to content (not sub directory) and now it is working.

**Comment by GeorgeWL** [comment]
This sounds like you just need to check out the docs of Hugo again 🙂
