### ISSUE TITLE
Submit button in contact form doesn't work

### ISSUE THREAD

**Issue by BenjaminLouis** [devcows/hugo-universal-theme#206]
Hi ! I used the hugo universal theme for [my website](https://www.benjaminlouis-stat.fr/)  ( by the way thanks for this theme).
My problem is that It seems that the submit button doesn't work in the [contact form](https://www.benjaminlouis-stat.fr/contact) as nothing happens when I click on it to activate my formspree email.
Maybe There is something I don't see but I don't know how to fix the problem.
Thanks

**Comment by ryanfox1985** [comment]
hello @BenjaminLouis, the theme is using https://formspree.io, and the Ajax POST is only for premium accounts, recently we update the theme with a flag to decide the POST Ajax or not (by default not Ajax).

If you want to use the free Fromspree account, I recommend to you to update to the theme to the latest version.

**Comment by ryanfox1985** [comment]
https://github.com/devcows/hugo-universal-theme/pull/203

**Comment by ryanfox1985** [comment]
here is your file: https://www.benjaminlouis-stat.fr/js/front.js and here the changes: https://github.com/devcows/hugo-universal-theme/blob/master/static/js/front.js#L22-L29

**Comment by BenjaminLouis** [comment]
Hello @ryanfox1985 
thanks a lot, it works perfectly now!

**Comment by ryanfox1985** [comment]
You are welcome, thanks for the theme usage.
