### ISSUE TITLE
I can't localize carousel (and clients, and features, etc)

### ISSUE THREAD

**Issue by herve-g** [devcows/hugo-universal-theme#207]
I tried to localise the carousel, by modifying yaml files, replacing "title" by "languages.fr.title", "description" by "language.fr.description", and so on.

But it does not work. Is that a bug? If not, what am I doing wrong?

Thank you.

**Comment by herve-g** [comment]
I found a way with the multilingual feature of Hugo. The carousel directory has a directory per language (en, fr, and so on), each directory contains a localized yaml file.

**Comment by Allexio** [comment]
Hi there @herve-g , I know ths is an old post, but do you mind detailing what you did (if you still remember?) I'm also stuck on this for my website...
How did you manage to configure the carousel directory to recognise language specific directories?

**Comment by Allexio** [comment]
Managed to make it work by copying layout partials from the moodlebox theme.
