### ISSUE TITLE
Create a tag for easier reference

### ISSUE THREAD

**Issue by sophokles73** [devcows/hugo-universal-theme#219]
Hi,

we would very much like to use this excellent theme for creating the new version of the web site of the Eclipse Hono [1] project. Would it be possible for you guys to create a (version) tag on a revision that you deem worthy to be used so that we can more easily reference it when generating the web site?

[1] https://www.eclipse.org/hono

Thanks,
Kai

**Comment by ryanfox1985** [comment]
Hi @sophokles73 ,

thanks to use the theme port to Hugo, it's true, we haven't a release plan yet. For this reason I created the tag [1.0.0](https://github.com/devcows/hugo-universal-theme/releases) and we will try to maintain the release plan.

Regards.
