### ISSUE TITLE
Changing the background img/photogrid.jpg to something else?

### ISSUE THREAD

**Issue by ngehani** [devcows/hugo-universal-theme#22]
I can change the img/photogrid n default.css to something else in the /theme folder but wondering if there is a way to change the background image without changing the original theme. Do I just have to add /static/img/background.jpg and /static/css/style.default.css under layouts and change the jumbtron and .home_carousel to point to the new image? Is this enough or is there something else to add in the HUGO config.toml file?

**Comment by ngehani** [comment]
Resolved: Need to copy the carousel.html to layouts/partial along with the style.default.css to static/css and this overrides the default theme elements. The partials are the important piece to copy. The img/.... should contain the assets you want to use.

**Comment by adrianmo** [comment]
I'm reopening the issue as a reminder to make the background image configurable.

**Comment by schuster-rainer** [comment]
@ngehani @adrianmo you can just copy your own /static/img/photogrid.jpg to your hugo site. But make it completely configurable will also be a nice plus. Maybe I'll give it a shot. If I start, I'll leave a comment here

**Comment by arunrajagopalan** [comment]
Folks. Great theme. But I can't change the background no matter what I do. Even deleting photo grid and all the images in static/img doesn't change the background. I am sure smart as hugo, its not fabriacating the images !! Clearing my browser doesn't help. Where are the images coming from ?

**Comment by GeorgeWL** [comment]
The images should only ever be coming from within the  `Images` folder inside the `/Static/` folder.  Hugo places these files in place in the correct places on build.

How are you implementing it? @schuster-rainer

I noticed for e.g. that Forestry.io has a bug which doesn't remove the original images unless you expressly tell it to replace all content files.

**Comment by arunrajagopalan** [comment]
Thanks George. We had a script that would test the site on a test bucket before deploying to a public bucket on S3. The baseURL wasn't changed. But most other URL were turned into absolute including the grid. After trashing that script and just changing baseURL before deploying solved the problem. 

Thanks for the note on img. I know make sure the all unwanted images are deleted along with the public directory before calling hugo

**Comment by GeorgeWL** [comment]
@adrianmo Closing this issue. 

That reminder should be it's own seperate issue, for ease of using the issue tracker more effectively.

**Comment by GeorgeWL** [comment]
https://github.com/devcows/hugo-universal-theme/issues/96
