### ISSUE TITLE
Fixed Top Bar

### ISSUE THREAD

**Issue by tattooseoul** [devcows/hugo-universal-theme#221]
Is there a way to have the top bar fixed on every page along with the logo and the menu?

**Comment by salim-b** [comment]
> Is there a way to have the top bar fixed

Non-sticky, you mean? Then I would apply the (unfortunately still unmerged) PR #177 and remove the [`position: sticky;`](https://github.com/devcows/hugo-universal-theme/blob/81f1ff9b1e93b86357cedcf97f79132f6376602c/static/css/style.default.css#L477) CSS rule (untested).

**Comment by sortecoevo** [comment]
hi, could you please provide more details and examples/snippets of how to implement tihis? I am new to bootstrap etc. so would greatly appreciate more guidance

**Comment by salim-b** [comment]
> hi, could you please provide more details and examples/snippets of how to implement tihis?

What exactly do you want to achieve? (https://github.com/devcows/hugo-universal-theme/pull/177 was merged meanwhile so we now use CSS only (i.e. no JS) to make the top bar sticky.)

**Comment by ryanfox1985** [comment]
The top bar menu is fixed in every page, I'm closing the issue.
