### ISSUE TITLE
image too big...

### ISSUE THREAD

**Issue by fanux** [devcows/hugo-universal-theme#222]
![image](https://user-images.githubusercontent.com/8912557/60884108-af2c3600-a27e-11e9-8145-57a64e03ce2c.png)

**Comment by martinctc** [comment]
I used the following as a work around. 
` <img src="image1.png" width ="50%">`

But I agree it would benefit to have something in the template to prevent the overflow!

**Comment by ryanfox1985** [comment]
it will be fixed by this PR: https://github.com/devcows/hugo-universal-theme/pull/369
