### ISSUE TITLE
How to customise description font size in landing page?

### ISSUE THREAD

**Issue by YonghuiDong** [devcows/hugo-universal-theme#225]
The fond size for description in the landing page is 21px, which is a bit large for me. I want to make it smaller, but I did not find the default value in css files.

Thanks for your help.

**Comment by ryanfox1985** [comment]
Same issue https://github.com/devcows/hugo-universal-theme/issues/159 , you can add your custom css and apply your style customization.

**Comment by ryanfox1985** [comment]
More info in this thread https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/14#post_14
