### ISSUE TITLE
Recent Posts broken on Hugo 0.58.0

### ISSUE THREAD

**Issue by sr0wpgxb6g** [devcows/hugo-universal-theme#226]
0.57.2 gave the error message:

> In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.

Now that 0.58.0 is out the recent posts on the front page is broken.

**Comment by salim-b** [comment]
PR #227 should fix this

**Comment by sr0wpgxb6g** [comment]
Fixed. Thank you.

**Comment by 1wilkens** [comment]
PR #227 is not merged so this is still broken on master. @salim-b Any chance of merging this?
