### ISSUE TITLE
Recent posts part of the page showing only one entry named Blogs

### ISSUE THREAD

**Issue by svetlemodry** [devcows/hugo-universal-theme#229]
Hi all!
Cloning the template and runnig the hugo server shows only one entry at the lower part of the page where the recent posts should be shown. I am running the latest version of HUGO v0.59.0 to test and see this.
Would be great to find out a fix. I am unfortunately not skilled enough in hugo templating to locate the trouble myself.
Cheers!
J

**Comment by salim-b** [comment]
See #227 and #228. I'm starting to get the feeling this repo is pretty much unmaintained.... :confused:

**Comment by ryanfox1985** [comment]
Hello it should be fixed at the release [1.0.1](https://github.com/devcows/hugo-universal-theme/releases/tag/1.0.1)

**Comment by svetlemodry** [comment]
Works great, thanks for the quick fix!!
