### ISSUE TITLE
Generate a RSS xml

### ISSUE THREAD

**Issue by ryanfox1985** [devcows/hugo-universal-theme#24]
Hi,

some people use the RSS xml feed for not enter to the blog and read the posts using some feed RSS client.  

Regards.

**Comment by penglish2** [comment]
That isn't quite a question, but as best I can tell, "all the things" get RSS feeds automatically - which is pretty fantastic.

eg: 

http://yoursite.com/index.xml

is an RSS feed of your main root. Ditto for each subdir.

However - the theme doesn't currently slap an RSS feed icon anywhere, which would be handy, as an option to turn on for any given page, or for the sitewide footer.

**Comment by adrianmo** [comment]
I agree with @penglish2. We could just add an RSS icon pointing to `index.xml`. Maybe we can implement it as part of the PR #29 as it's adding social icons as well.

**Comment by schuster-rainer** [comment]
Added to #57

**Comment by GeorgeWL** [comment]
@schuster-rainer 

Isn't this a core feature of Hugo?
