### ISSUE TITLE
customize abstract content for each blog post

### ISSUE THREAD

**Issue by xiaoouwang** [devcows/hugo-universal-theme#241]
Hello thank you for this great theme. I'm wondering if there are any options to change the default text for each blog post on the homepage and on the blog page. 

Any option will be helpful like maximum number of words etc...

Keep up the good work !

**Comment by ryanfox1985** [comment]
Hello, this feature is already provided by Hugo, recent posts are using `.Summary ` https://gohugo.io/content-management/summaries. I created a PR with a demo how to do it.
