### ISSUE TITLE
recent_posts is not working

### ISSUE THREAD

**Issue by benzwt** [devcows/hugo-universal-theme#249]
According to the content of  layouts/partials/recent_posts.html
it should show 4 most recent post in the recent_posts section.
Somehow, the exampleSite only show one post, and the post
isn't right.

**Comment by salim-b** [comment]
I can't reproduce your problem. 

`layouts/partials/recent_posts.html` shows exactly 4 posts as it should when I build the `exampleSite` of the current master branch:

![Screenshot_2019-12-10 Universal](https://user-images.githubusercontent.com/20040931/70528992-6a673c80-1b47-11ea-8e7d-f44b530a8054.png)

**Comment by ryanfox1985** [comment]
I think the error is related with the Hugo Version. Please @benzwt can you report the hugo version that are you using?

**Comment by benzwt** [comment]
> I think the error is related with the Hugo Version. Please @benzwt can you report the hugo version that are you using?

Hugo Static Site Generator v0.61.0-DEV linux/amd64 BuildDate: unknown

**Comment by benzwt** [comment]
> I can't reproduce your problem.
> 
> `layouts/partials/recent_posts.html` shows exactly 4 posts as it should when I build the `exampleSite` of the current master branch:
> 
> ![Screenshot_2019-12-10 Universal](https://user-images.githubusercontent.com/20040931/70528992-6a673c80-1b47-11ea-8e7d-f44b530a8054.png)

This is what I see
![universal](https://user-images.githubusercontent.com/1032178/70544145-8fd76300-1ba6-11ea-8c5e-290400d7a153.png)
Please shed some light on how to trace the code.

**Comment by salim-b** [comment]
> Hugo Static Site Generator v0.61.0-DEV linux/amd64 BuildDate: unknown

Well, current stable version (the one I'm using) would be `Hugo Static Site Generator v0.60.0 linux/amd64`. Could you give it a try?

**Comment by benzwt** [comment]
> > Hugo Static Site Generator v0.61.0-DEV linux/amd64 BuildDate: unknown
> 
> Well, current stable version (the one I'm using) would be `Hugo Static Site Generator v0.60.0 linux/amd64`. Could you give it a try?

**I still cannot see the right recent_posts.**

Here is what I did in my ubuntu 18.04 LTS

prompt>hugo version
Hugo Static Site Generator v0.60.0-F2DEA9B0 linux/amd64 BuildDate: 2019-11-27T10:10:48Z
prompt>cd hugo-universal-theme/exampleSite
prompt>git pull && git log --pretty=oneline | head -n 3
e6d8c2be7cd613647d320dffa9b043b90784c084 replace site variable by absURL function (#248)
553edb0459b575b396d037729a3168194147568f use relative home URL (#247)
a0b5d70608296c44781899de97cf48382fca40f5 Updated with relURL (#244)
prompt> hugo server

**Comment by salim-b** [comment]
> **I still cannot see the right recent_posts.**

Sorry that switching to stable Hugo v0.60 didn't help. Meanwhile I've update to stable Hugo v0.61.0 and the exampleSite still works fine for me.

(I'm using the snap package of Hugo on Ubuntu 16.04, but I don't think that your issue is related to your OS)

May be a bit far-fetched, but are you sure none of your browser addon's (ABP etc.) is blocking the content?

**Comment by benzwt** [comment]
> > **I still cannot see the right recent_posts.**
> 
> Sorry that switching to stable Hugo v0.60 didn't help. Meanwhile I've update to stable Hugo v0.61.0 and the exampleSite still works fine for me.
> 
> (I'm using the snap package of Hugo on Ubuntu 16.04, but I don't think that your issue is related to your OS)
> 
> May be a bit far-fetched, but are you sure none of your browser addon's (ABP etc.) is blocking the content?

I my browser from firefox to chrome but the problem still presist.
Would you give me some idea to trace the problem ?

here is the html source for the recent_posts

<section class="bar background-white no-mb">
    <div class="container">
        <div class="col-md-12">
            <div class="heading text-center">
                <h2>From our blog</h2>
            </div>
            <p class="lead">
              Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
            </p>
            <div class="row">            
                <div class="col-md-3 col-sm-6">
                    <div class="box-image-text blog">
                        <div class="top">
                            <div class="image" style="overflow:hidden">                               
                                <img src="http://localhost:1313/img/placeholder.png" class="img-responsive" alt="">
                             </div>
                            <div class="bg"></div>
                            <div class="text">
                                <p class="buttons">
                                    <a href="http://localhost:1313/blog/" class="btn btn-template-transparent-primary"><i class="fa fa-link"></i> Read more</a>
                                </p>
                            </div>
                        </div>

                        <div class="content">
                            <h4><a href="http://localhost:1313/blog/">Blogs</a></h4>
                            <p class="author-category">
                            
                            on October 10, 2015
                            </p>
                            <p class="intro"></p>
                            <p class="read-more">
                              <a href="http://localhost:1313/blog/" class="btn btn-template-main">Continue reading</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</section>

**Comment by salim-b** [comment]
> I my browser from firefox to chrome but the problem still presist.
> Would you give me some idea to trace the problem ?
> 
> here is the html source for the recent_posts
> 
> [html code](https://pastebin.com/xWG7xRWH)

I don't think you're on par with the current master branch... here's a diff between the HTML as it was rendered on my side (on the left) and the HTML you've posted (on the right): https://www.diffchecker.com/TGHW3R1Z

If you freshly clone the repo to an empty dir and then build the exampleSite, does the issue persist?

**Comment by benzwt** [comment]
> > I my browser from firefox to chrome but the problem still presist.
> > Would you give me some idea to trace the problem ?
> > here is the html source for the recent_posts
> > [html code](https://pastebin.com/xWG7xRWH)
> 
> I don't think you're on par with the current master branch... here's a diff between the HTML as it was rendered on my side (on the left) and the HTML you've posted (on the right): https://www.diffchecker.com/TGHW3R1Z
> 
> If you freshly clone the repo to an empty dir and then build the exampleSite, does the issue persist?

Finally, the recent_posts shows correctly.

I used **hugo new site quickstart** to create a site and **git clone hugo-universal-theme under the folder themes**.  After had the site removed and recreated the fresh environment, everything was **back to normal**.

Thanks for the responsive reply.

**Comment by ryanfox1985** [comment]
thanks @benzwt  for reporting.
