### ISSUE TITLE
Pipeline error when pushing site to gitlab

### ISSUE THREAD

**Issue by nadershakhshir** [devcows/hugo-universal-theme#250]
This is my very first issue here so excuse me if i didn't sound very professional.

I am facing the below errors when trying to push the website to the gitlab repository. Can you help please?

ERROR 2019/12/11 12:53:17 Failed to add template "theme/partials/head.html" in path "/builds/debugnomad/www/hugo-universal-theme/layouts/partials/head.html": template: theme/partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 12:53:17 Failed to add template "theme/partials/recent_posts.html" in path "/builds/debugnomad/www/hugo-universal-theme/layouts/partials/recent_posts.html": template: theme/partials/recent_posts.html:18: function "site" not defined
ERROR 2019/12/11 12:53:17 partials/head.html : template: partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 12:53:17 partials/recent_posts.html : template: partials/recent_posts.html:18: function "site" not defined
ERROR 2019/12/11 12:53:17 theme/partials/head.html : template: theme/partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 12:53:17 theme/partials/recent_posts.html : template: theme/partials/recent_posts.html:18: function "site" not defined
Started building sites ...
ERROR 2019/12/11 12:53:17 Error while rendering "page": template: _default/single.html:4:5: executing "_default/single.html" at <partial "head.html" ...>: error calling partial: template: "partials/head.html" is an incomplete or empty template
ERROR: Job failed: exit code 1

**Comment by ryanfox1985** [comment]
Hi @nadershakhshir  it's difficult to figure out where is the problem with this short trace, can you attach all the logs?, if there is something confidential, you can obfuscate the line.

**Comment by nadershakhshir** [comment]
> Hi @nadershakhshir it's difficult to figure out where the problem is with this short trace, can you attach all the logs?, if there is something confidential, you can obfuscate the line.

[0KRunning with gitlab-runner 12.5.0 (577f813d)
[0;m[0K  on docker-auto-scale fa6cab46
[0;msection_start:1576070161:prepare_executor
[0K[0KUsing Docker executor with image publysher/hugo ...
[0;m[0KPulling docker image publysher/hugo ...
[0;m[0KUsing docker image sha256:fd1360f988958713b155bd8cd39875ee9398abadf9c91a8ba30efa0538727e42 for publysher/hugo ...
[0;msection_end:1576070185:prepare_executor
[0Ksection_start:1576070185:prepare_script
[0KRunning on runner-fa6cab46-project-15608316-concurrent-0 via runner-fa6cab46-srm-1576070117-a1f137ac...
section_end:1576070190:prepare_script
[0Ksection_start:1576070190:get_sources
[0K[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/debugnomad/www/.git/
[32;1mCreated fresh repository.[0;m
From https://gitlab.com/debugnomad/www
 * [new ref]         refs/pipelines/102296531 -> refs/pipelines/102296531
 * [new branch]      master                   -> origin/master
[32;1mChecking out 5bda1446 as master...[0;m

[32;1mUpdating/initializing submodules recursively...[0;m
Submodule 'hugo-universal-theme' (https://github.com/devcows/hugo-universal-theme.git) registered for path 'hugo-universal-theme'
Cloning into '/builds/debugnomad/www/hugo-universal-theme'...
Submodule path 'hugo-universal-theme': checked out 'e6d8c2be7cd613647d320dffa9b043b90784c084'
Entering 'hugo-universal-theme'
section_end:1576070193:get_sources
[0Ksection_start:1576070193:restore_cache
[0Ksection_end:1576070194:restore_cache
[0Ksection_start:1576070194:download_artifacts
[0Ksection_end:1576070196:download_artifacts
[0Ksection_start:1576070196:build_script
[0K[32;1m$ hugo[0;m
ERROR 2019/12/11 13:16:36 Failed to add template "partials/head.html" in path "/builds/debugnomad/www/layouts/partials/head.html": template: partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 13:16:36 Failed to add template "theme/partials/head.html" in path "/builds/debugnomad/www/hugo-universal-theme/layouts/partials/head.html": template: theme/partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 13:16:36 Failed to add template "theme/partials/recent_posts.html" in path "/builds/debugnomad/www/hugo-universal-theme/layouts/partials/recent_posts.html": template: theme/partials/recent_posts.html:18: function "site" not defined
ERROR 2019/12/11 13:16:36 partials/head.html : template: partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 13:16:36 theme/partials/head.html : template: theme/partials/head.html:10: unexpected "=" in operand
ERROR 2019/12/11 13:16:36 theme/partials/recent_posts.html : template: theme/partials/recent_posts.html:18: function "site" not defined
Started building sites ...
ERROR 2019/12/11 13:16:36 Error while rendering "page": template: _default/single.html:4:5: executing "_default/single.html" at <partial "head.html" ...>: error calling partial: template: "partials/head.html" is an incomplete or empty template
section_end:1576070197:build_script
[0Ksection_start:1576070197:after_script
[0Ksection_end:1576070199:after_script
[0Ksection_start:1576070199:upload_artifacts_on_failure
[0Ksection_end:1576070200:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit code 1
[0;m

**Comment by nadershakhshir** [comment]
Hi @ryanfox1985 

Please find up the logs.

**Comment by ryanfox1985** [comment]
hello @nadershakhshir its hard to figure out with these logs.

But I saw something, you are using this docker image to build the static site:
- https://hub.docker.com/r/publysher/hugo
- https://github.com/publysher/docker-hugo

I saw on github this image is not longer maintained:

![image](https://user-images.githubusercontent.com/1152728/70715627-fbc2e400-1cea-11ea-8b52-61b1790514bd.png)

Last commit 2 years ago and maybe using hugo v0.22, it's a very old version, I think the version most recent is 0.6X

Perhaps the error is related with the Hugo version, can you try to use a more recent version?

**Comment by nadershakhshir** [comment]
Hi @ryanfox1985 

Thank you for the idea, i actually was able to successfully solve it by changing the yaml file and also using the latest Hugo version...

**Comment by ryanfox1985** [comment]
ok, thanks!
