### ISSUE TITLE
How to hide the date in single pages?

### ISSUE THREAD

**Issue by ctindel** [devcows/hugo-universal-theme#252]
For some reason new pages that I create are having a date of JANUARY 1, 0001 at the top right corner.  I see where I can omit the author parameter but how do I tell universal that I don't want a date on the page either?

**Comment by ryanfox1985** [comment]
Hello @ctindel, with the current version is not allowed, I created a PR to solve that. Thanks for report and the usage of this port.

**Comment by ctindel** [comment]
Hi @ryanfox1985 thanks for doing that.  Is this something that would be going in soon?  

I'm new to hugo, can i just make these same changes in my theme files and get the functionality now?

**Comment by salim-b** [comment]
> I'm new to hugo, can i just make these same changes in my theme files and get the functionality now?

Sure, just apply the changes from https://github.com/devcows/hugo-universal-theme/pull/253

Assuming you initalized your project the [recommended way](https://gohugo.io/getting-started/quick-start/#step-2-create-a-new-site), you should copy the relevant files from the `themes/` subfolder to your project root and then make the changes there (the `/` folder takes precedence over `themes/` subfolder). E.g. copy `themes/hugo-universal-theme/layouts/_default/list.html` to `layouts/_default/list.html` and then add [these changes](https://github.com/devcows/hugo-universal-theme/pull/253/files#diff-3db8db7226d7f28bb43b59ce30ad6157) to that file.

**Comment by ryanfox1985** [comment]
I merged the PR, so now is available on master, @ctindel you only need to pull again the theme.

**Comment by ctindel** [comment]
Nice thanks @ryanfox1985
