### ISSUE TITLE
footer-recent posts

### ISSUE THREAD

**Issue by fazeln** [devcows/hugo-universal-theme#255]
I  want recent posts only appear in my Home page and remove them from the footer all the pages. How should I do it?

**Comment by salim-b** [comment]
If you're not already overriding the theme's `footer.html`, do so by copying `themes/hugo-universal-theme/layouts/partials/footer.html` to `partials/footer.html` and then edit that file to include another condition for the `recent_posts.html` partial inclusion.

I'd add a simple `{{ if .IsHome }}` statement.

To do so, change line 18

https://github.com/devcows/hugo-universal-theme/blob/e45210fd7697670746444928a15e2e28eaf370e0/layouts/partials/footer.html#L18

to 

```html
            {{ if isset .Site.Params "recent_posts" }} {{ if .Site.Params.recent_posts.enable }} {{ if .IsHome }}
```

as well as line 41

https://github.com/devcows/hugo-universal-theme/blob/e45210fd7697670746444928a15e2e28eaf370e0/layouts/partials/footer.html#L41

to 

```html
            {{ end }} {{ end }} {{ end }}
```
