### ISSUE TITLE
Overriding navbar-brand CSS

### ISSUE THREAD

**Issue by ctindel** [devcows/hugo-universal-theme#261]
Our logo image sticks down below the navbar slightly and gets covered by the next part of the website.  I've found that if i change the .navbar-brand padding to "10px 15px;" it looks good.

But i don't want to be changing theme css files.   I thought that I could put this in the static/css/custom.css file and it would override but that doesn't seem to be working (though i can see that other parts of my custom.css are fine).

```
.navbar-brand {
  padding: 0px 15px;
}
```

I'm no CSS expert though.  How do I override this padding without changing the theme files?

**Comment by ctindel** [comment]
Hmmm, it seems I needed to restart hugo after making the CSS change and that made the override work.

**Comment by salim-b** [comment]
> Hmmm, it seems I needed to restart hugo after making the CSS change and that made the override work.

Maybe just starting `hugo server` with [`--disableFastRender`](https://gohugo.io/commands/hugo_server/) does the trick, too...
