### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by jakegalson** [devcows/hugo-universal-theme#262]
I have tried adding custom css to /static/css/custom.css. However, it does not appear to be being used. When I build the site, and inspect, my custom css is not included.

**Comment by ryanfox1985** [comment]
@jakegalson do you have link to the repo?

**Comment by ryanfox1985** [comment]
I tested in demo site and it worked:

https://devcows.github.io/hugo-universal-theme/css/custom.css
