### ISSUE TITLE
Theme do not work

### ISSUE THREAD

**Issue by mxlit** [devcows/hugo-universal-theme#265]
config.toml
<pre>
baseurl = "https://example.org"
title = "Universal"
theme = "hugo-universal-theme"
themesDir = "../.."
</pre>
result:
<pre>
$ hugo server
Error: module "hugo-universal-theme" not found; either add it as a Hugo Module or store it in "/home/ltgr/Desktop".: module does not exist
$
</pre>
config.toml
<pre>
baseurl = "https://example.org"
title = "Universal"
theme = "hugo-universal-theme"
themesDir = "themes"
</pre>
result:
<pre>
$ hugo server
Built in 41 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:18:11: executing "index.html" at <partial "carousel.html" .>: error calling partial: "/home/ltgr/Desktop/HugoSite/univ/themes/hugo-universal-theme/layouts/partials/carousel.html:3:10": execute of template failed: template: partials/carousel.html:3:10: executing "partials/carousel.html" at <len .Site.Data.carousel>: error calling len: len of untyped nil
$ 
</pre>
config.toml
<pre>
[params.carousel]
    enable = false
</pre>
result:
<pre>
$ hugo server
Built in 38 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:20:11: executing "index.html" at <partial "features.html" .>: error calling partial: "/home/ltgr/Desktop/HugoSite/univ/themes/hugo-universal-theme/layouts/partials/features.html:3:10": execute of template failed: template: partials/features.html:3:10: executing "partials/features.html" at <len .Site.Data.features>: error calling len: len of untyped nil
$
</pre>

**Comment by ibakirov** [comment]
@mxlit change themesDir = "/themes" and it will work

**Comment by maco** [comment]
`themesDir = "/themes"` got me the same "not found" error as the initial one. Removing the `/` got the "failed to render pages" one.

**Comment by ibakirov** [comment]
@maco please share your configs and version you use. I'm on hugo v0.76.5-60F0725B windows/amd64 and using this theme without any issues

**Comment by maco** [comment]
I copied the config.toml from the exampleSite directory, figuring that'd be a good starting point. Changing the themesDir (based on your comment) is the only change I made to it. I'm using hugo 0.80.0 on Mac OS 11.

**Comment by ibakirov** [comment]
@maco just checked with your version and it works also. Please re-check your steps. Here is mine:

`>hugo version`
Hugo Static Site Generator v0.80.0-792EF0F4 windows/amd64 BuildDate: 2020-12-31T13:37:57Z

`>hugo new site test`
Congratulations! Your new Hugo site is created in test.

`>cd test`

`test>git clone https://github.com/devcows/hugo-universal-theme themes\hugo-universal-theme`
Cloning into '.\themes\hugo-universal-theme'...

`test>xcopy /e /y .\themes\hugo-universal-theme\exampleSite\* .`
57 File(s) copied

`test> edit config.toml file the line: themesDir="themes" and save`

`test>hugo server`
Start building sites …

                   | EN
-------------------+------
  Pages            |  36
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 103
  Processed images |   0
  Aliases          |  14
  Sitemaps         |   1
  Cleaned          |   0

Built in 86 ms

**Comment by ryanfox1985** [comment]
Hello, finally could you setup the theme?

**Comment by ryanfox1985** [comment]
I closed the issue for inactivity, @ibakirov posted the correct steps to compile the site with Hugo.

**Comment by markus-96** [comment]
hello, I had the same issue and this resolved it. thanks!
But why is this not mentioned anywhere? In the documentation it is said that the exampleSite dir would contain a working site, but with this it does apparently not.
