### ISSUE TITLE
Creating Sub-menus

### ISSUE THREAD

**Issue by pennirae** [devcows/hugo-universal-theme#266]
Trying to do sub-menus in theme Ananke & I have the following for my menus:

title = "SEDHYD Website"
theme = "ananke"
googleAnalytics = "UA-123026999-1"
[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "Committees"
    name = "Committees"
    pre = "<i class='fa fa-road'></i>"
    url = "/Committees/"
    weight = -100	

  [[menu.main]]
    identifier = "SEDHYD 2003"
    name = "SEDHYD 2023"
    pre = "<i class='fa fa-road'></i>"
    url = "/SEDHYD_2023/"
    weight = -80

  [[menu.main]]
    identifier = "Proceedings"
    name = "Proceedings"
    pre = "<i class='fa fa-road'></i>"
    url = "/proceedings/"
    weight = -90

  [[menu.main]]
    parent = "Proceedings"
    name = "Current"
    url = "/proceedings/current/"
	
[[menu.main]]
    identifier = "Contact Us"
    name = "Contact Us"
    pre = "<i class='fa fa-road'></i>"
    url = "/contact/"
    weight = -70

Under Proceedings I tried to add a submenu "Current"; did not work.  Is this the way to do sub-menus when using the Ananke theme?  If not, how would I get sub-menus?

Thanks

**Comment by salim-b** [comment]
This is the **`hugo-universal-theme`** 😐

**Comment by ryanfox1985** [comment]
this was introducced in this PR https://github.com/devcows/hugo-universal-theme/pull/307 and released in https://github.com/devcows/hugo-universal-theme/releases/tag/1.2.1

So now the theme allows to create sub-menus.

![image](https://user-images.githubusercontent.com/1152728/128595068-20211aa2-848b-4892-b4da-2ca5d9fefbc9.png)
