### ISSUE TITLE
Unable to filter posts by author

### ISSUE THREAD

**Issue by caiocco** [devcows/hugo-universal-theme#269]
I'm using this theme for a website (https://www.commu.site), but I am not able to filter blog posts by author. Any clues for files and/or parameters I should check?

Thank you in advance!

**Comment by salim-b** [comment]
This [taxonomy](https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy) is not implemented in this theme (yet), only _categories_ and _tags_, see [`layouts/partials/widgets`](https://github.com/devcows/hugo-universal-theme/tree/master/layouts/partials/widgets).

I guess a PR introducing proper author taxonomy support would be welcome!

**Comment by caiocco** [comment]
Okay, I managed to fix the issue by myself, albeit I don't know how to make a PR. One willing to add taxonomy for authors should add into "config.toml":

```
[taxonomies]
	# Add extra taxonomies
	# "categories" and "tags" are the default
	category = "categories"
	tag = "tags"
	author = "author"
```
And then modify "layouts/_default/list.html", line 44 or so:

```
                                          {{ if isset .Params "author" }}
                                          {{ if gt (len .Params.author) 0 }}
                                          {{ i18n "authorBy" }} <a href="{{ "author/" | relURL }}{{ index .Params.author | urlize | lower }}">{{ index .Params.author }}</a>
                                          {{ end }}
                                          {{ end }}
```
