### ISSUE TITLE
Please switch to safe baseURL for example config

### ISSUE THREAD

**Issue by digitalcraftsman** [devcows/hugo-universal-theme#27]
Apparently a scammer has registered the default base url genreated by hugo ("http://replace-this-with-your-hugo-site.com") and has some malware, ads, etc on it. See: spf13/hugoThemes#171.

To avoid such abuse in the future I would recommend to switch to a base url like "https://www.example.com/".

Thanks

**Comment by adrianmo** [comment]
Thanks for the heads up @digitalcraftsman. Updating the baseURL...

Best,
-Adrian
