### ISSUE TITLE
logo sizes

### ISSUE THREAD

**Issue by sortecoevo** [devcows/hugo-universal-theme#277]
hi, 
currently the sizes of both versions of the logo are fixed - is there a way to make them scale with the page?
Also, is there a way to use higher resolution file (currently it blows up to a large image) or at least to be able to set the size e.g. as percentage of navbar height ?

**Comment by ryanfox1985** [comment]
@sortecoevo do you have a site to able to see the problem? Perhaps with css, the problem can be resolved.
