### ISSUE TITLE
Add social section / info

### ISSUE THREAD

**Issue by stephlocke** [devcows/hugo-universal-theme#28]
This theme is nifty, but it's missing some twitter links etc. Would it be possible to add these in?

**Comment by adrianmo** [comment]
Hi @stephlocke,

Yes, I think it's a good idea. We will keep this issue open as a reminder. 

Where would you place the social links/icons within the theme?

Thanks.

-Adrián

**Comment by adrianmo** [comment]
I just saw the PR #29. I will review it today.

**Comment by schuster-rainer** [comment]
Added the necessary enhancements in #57 this one can be closed on merge

**Comment by GeorgeWL** [comment]
It's all merged into main now. Closing.
