### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by sangmyung-hp** [devcows/hugo-universal-theme#284]
![Detail Specification](https://user-images.githubusercontent.com/76457662/104864960-f029fe00-597d-11eb-8a06-a308f5d3224c.PNG

![CertificationGuide](https://user-images.githubusercontent.com/76457662/104864994-0a63dc00-597e-11eb-811a-431972387ee0.PNG)

![Detail Specification](https://user-images.githubusercontent.com/76457662/104865010-164f9e00-597e-11eb-9db4-b4affd492157.PNG)

![Detail Specification](https://user-images.githubusercontent.com/76457662/104865023-25cee700-597e-11eb-8a52-436a20620a79.PNG)

![table](https://user-images.githubusercontent.com/76457662/104865040-2ff0e580-597e-11eb-93ba-c1163f8345c0.jpg)

![Detail Specification](https://user-images.githubusercontent.com/76457662/104865056-40a15b80-597e-11eb-83e9-e8e073a67c51.PNG)

![5pv_render_new_crop](https://user-images.githubusercontent.com/76457662/104865099-6890bf00-597e-11eb-9a37-289bdd9a8545.jpg)

**Comment by salim-b** [comment]
Please stop the spam!
