### ISSUE TITLE
Small Purge and Pressurization Solutions_Applications Review

### ISSUE THREAD

**Issue by sangmyung-hp** [devcows/hugo-universal-theme#287]
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_01](https://user-images.githubusercontent.com/76457662/106410142-85041f80-6485-11eb-852b-f7535c733a84.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_02](https://user-images.githubusercontent.com/76457662/106410143-85041f80-6485-11eb-9dcc-b66576082ca3.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_03](https://user-images.githubusercontent.com/76457662/106410144-859cb600-6485-11eb-8d85-c012c07a8a44.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_04](https://user-images.githubusercontent.com/76457662/106410146-86354c80-6485-11eb-9c2d-5839e6f2fcdc.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_05](https://user-images.githubusercontent.com/76457662/106410147-86354c80-6485-11eb-9b58-f9a006c37851.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_06](https://user-images.githubusercontent.com/76457662/106410132-82092f00-6485-11eb-9c61-a6407ebd18ef.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_07](https://user-images.githubusercontent.com/76457662/106410137-83d2f280-6485-11eb-987b-4efd8f5e725a.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_08](https://user-images.githubusercontent.com/76457662/106410138-83d2f280-6485-11eb-8c21-ea51070c592e.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_09](https://user-images.githubusercontent.com/76457662/106410139-846b8900-6485-11eb-8f25-e7271c3205b5.jpg)
![3 Small Purge and Pressurization Solutions_Applications Review_페이지_10](https://user-images.githubusercontent.com/76457662/106410141-846b8900-6485-11eb-91fd-8beb6734045c.jpg)

**Comment by salim-b** [comment]
@ryanfox1985 Could you please block the user @sangmyung-hp ? Thanks. That person (or bot?) continues to [fill the issue tracker with nonsense spam issues](https://github.com/devcows/hugo-universal-theme/issues?q=is%3Aissue+author%3Asangmyung-hp) despite my [request to stop it](https://github.com/devcows/hugo-universal-theme/issues/284#issuecomment-762541057). 🙄

**Comment by ryanfox1985** [comment]
@salim-b I blocked him.
