### ISSUE TITLE
Carousel for testimonials

### ISSUE THREAD

**Issue by mdozmorov** [devcows/hugo-universal-theme#288]
Is it possible to make panels in the "Testimonials" section rotate automatically, like the "Carousel" section? It seems the `owl-carousel` class is there, but it doesn't work on panels. Please, help. Thanks!

**Comment by ryanfox1985** [comment]
Hello, sorry for the late reply, yes I think is possible, I think is triggered via Javascript.

**Comment by ryanfox1985** [comment]
It could be a nice feature have several options for all the home page carousels to enable the autoplay.

https://github.com/devcows/hugo-universal-theme/blob/master/static/js/front.js#L128

**Comment by mdozmorov** [comment]
If this can be enabled/disabled in the config file, that would be great.

**Comment by ryanfox1985** [comment]
@mdozmorov I added the options to able to configure the carousels via `config.toml`. Enjoy!

**Comment by ctindel** [comment]
Just FYI @ryanfox1985 you misspelled the word in the config.toml and in the matching code itself.

carouselTestimonals

should be

carouselTestimonials

**Comment by ryanfox1985** [comment]
thanks for notify.
