### ISSUE TITLE
Font awesome icons issue with Hugo 0.82.0

### ISSUE THREAD

**Issue by jules32** [devcows/hugo-universal-theme#291]
Hello – thank you for this great theme! 

I've just upgraded to Hugo 0.82.0 and re-installed your theme on April 21, 2021. I've noticed an issue with the Font Awesome icons – they display correctly on the home page but not on the blog page's tags.

Here is my deployed netlify site: [home page](https://upgrade-hugo--sad-williams-fa509f.netlify.app) and [blog page](https://upgrade-hugo--sad-williams-fa509f.netlify.app/blog/), deployed from this [repo branch](https://github.com/openscapes/website/tree/upgrade-hugo). 

Thank you!

**Comment by ryanfox1985** [comment]
Hello, I can see an incoherence:

main page is using an old version of font-awesome => fa fa-lightbulb-o

blogs is using a modern one => fas fa-tags instead of fa fa-tag

**Comment by ryanfox1985** [comment]
it seems you have a mix with versions => https://github.com/devcows/hugo-universal-theme/blob/0da0cd586b31910adacab46fe1f12dcec1ee6e72/exampleSite/data/features/consulting.yaml#L3 

We have updated fontawe some icons library.

**Comment by jules32** [comment]
Thank you for your reply. 

Is the incoherence something that I should fix myself, or will this be fixed by the updates in the fontawesome icons library? Should I reinstall the theme?

**Comment by ryanfox1985** [comment]
You have 2 options:

- Reinstall the theme and update your markdown references in `config.toml` and  markdown as well. take a look this PR: https://github.com/devcows/hugo-universal-theme/pull/234/files
- Or use an old theme version (1.0.2) => https://github.com/devcows/hugo-universal-theme/releases

**Comment by jules32** [comment]
Thank you – I was able to fix it with the first option.

**Comment by ryanfox1985** [comment]
you are welcome!
