### ISSUE TITLE
Formspree allows 50 submissions/mo

### ISSUE THREAD

**Issue by iaeiou** [devcows/hugo-universal-theme#316]
Hi there,

the doc of Universal theme [says that Formspress allows 1000 submissions / month](https://github.com/devcows/hugo-universal-theme#contact-form).

Unfortunately, iIt's seems like it's [only 50 submissions / month now](https://formspree.io/plans) in the free Plan

**Comment by ryanfox1985** [comment]
Hello @iaeiou, good catch. I think the best to address this is have a generic text like:

The theme is using formspree and the submissions for the free plan are limited, checkout the plans.

What do you think? Can you open a PR?

**Comment by iaeiou** [comment]
Hi @ryanfox1985 ,

> What do you think? Can you open a PR?

Yes, I will propose a PR asap

**Comment by RoneoOrg** [comment]
> Yes, I will propose a PR asap

Done! Sorry for the delay
