### ISSUE TITLE
Putting telephone in the top menu results in ZgotmplZ

### ISSUE THREAD

**Issue by Faalagorn** [devcows/hugo-universal-theme#321]
Putting the following code results in phone number not displaying instead a `#ZgotmplZ` appears in URL when hovered: 
```
[[menu.topbar]]
    weight = 1
    name = "Telefon"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"
```
Changing `tel` to `mailto` works, and using `tel` in other places works as well, so it seems to be an issue with top bar only. 

According to https://stackoverflow.com/questions/14765395/why-am-i-seeing-zgotmplz-in-my-go-html-template-output it is unsafe content reaching a CSS or URL context at runtime – might be something easy to fix, but unfortunately, I have no idea how to do it. :(

**Comment by ryanfox1985** [comment]
thanks for reporting, using safeURL helper resolves the problem.

Also I added the phone icon at the top header buttons in the demo site, https://devcows.github.io/hugo-universal-theme
