### ISSUE TITLE
Too many bugs - can't even server -D

### ISSUE THREAD

**Issue by 4044ever** [devcows/hugo-universal-theme#328]
Theme has too many bugs. Themes need to work out of the box.

There is also a config.toml missing, the one from /example/ ain't working.

```
G:\web\Hugo\pizza>hugo server -D
Start building sites …
hugo v0.88.1-5BC54738+extended windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
WARN 2021/10/03 21:28:45 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:17:11: executing "index.html" at <partial "carousel.html" .>: error calling partial: "G:\web\Hugo\pizza\themes\hugo-universal-theme\layouts\partials\carousel.html:2:10": execute of template failed: template: partials/carousel.html:2:10: executing "partials/carousel.html" at <len .Site.Data.carousel>: error calling len: reflect: call of reflect.Value.Type on zero Value
Built in 182 ms
```

Pity, otherwise I like the design

Suggestion: Include a working config.toml

And no, this does not fix it:
```
[params.carousel]
    enable = false
```

**Comment by ryanfox1985** [comment]
Hello @4044ever , could you post the entire config.toml?

**Comment by 4044ever** [comment]
I tried a few settings, this is the last (I believe) bevor I moved on. Hope Pastebin is OK, if not I can post it later. 

What would be nice is a fail-safe config.toml suggestion. Some themes have a copy&paste starter config. Yes, I like to try your theme again.

https://pastebin.com/z82nrRdR

**Comment by ryanfox1985** [comment]
thanks for posting, the config.toml seems good. I think your errors is because there is no project structure (I think some folders are expected). 
I was wondering if you can post your project directory (I mean `ls -R`)

Btw, Have you seen the example site? 

https://github.com/devcows/hugo-universal-theme/tree/master/exampleSite

It's used to build the demo site: https://devcows.github.io/hugo-universal-theme

**Comment by ryanfox1985** [comment]
I figured out what was your problem, you don't have the folder present `./data/carousel` and you have enabled the carousel.

To disable the home page carousel, the settings are explained here https://github.com/devcows/hugo-universal-theme#carousel , this is an example:

```
[params.carouselHomepage]
    enable = false
```

**Comment by 4044ever** [comment]
More errors coming... But this helps:

```
[params.*****]
    enable = false
```
Most of the params. need to be set to false. It's finally working.

Basically all the 20 or so themes I tried so far work out of the box. I really suggest you put a works-out-of-the-box config.toml online as a copy&paste text file.
