### ISSUE TITLE
/exampleSite/ fresh install - 404 page not found

### ISSUE THREAD

**Issue by 4044ever** [devcows/hugo-universal-theme#330]
2nd bug encountered:

**Problem:**
Fresh install, nothing touched:

`.....\hugo-universal-theme\exampleSite>hugo server -D`

or

`.....\hugo-universal-theme\exampleSite>hugo server --themesDir ../..`

at localhost:1313 >` 404 page not found`

**Expected outcome:**
A functionable sample site

**Comment by ryanfox1985** [comment]
Could you check the logs after run `hugo server -D`, as @dibotak says there is one line with the url available: `Web Server is available at http://localhost:1313/hugo-universal-theme/`

**Comment by ryanfox1985** [comment]
I consider no issue at all.
