### ISSUE TITLE
Cannot find how to modify BLOGS header + Menu behaviour question

### ISSUE THREAD

**Issue by diapason-consulting** [devcows/hugo-universal-theme#353]
Dear all, 

My site is  https://diapason.consulting

1. For some reason, the header of the blog page is called BLOGS with a S. 
I did not do that :( it's also there in the demo site.

Trying to fix that but I cannot find the word 'blogs' anywhere in the whole folder?

2. I'm not a big fan of the way on landing the two "composite" menu items (services and applications) are like already selected (blue rectangle fill). I'd like it to be consistent:  nothing pre-selected when "landing" on the site, but then if navigating to one of the applications or one of the services page - then the corresponding top menu should be blue. Any help or idea welcome on that :)

THX

**Comment by ryanfox1985** [comment]
Hello, for the point 1 plurals I created the PR, there is an option in Hugo to not pluralize, I added an example to the sample site.

Regarding point 2, I have no idea without the code, could you paste here the menu config section?

**Comment by diapason-consulting** [comment]
Sure thanks a lot

`baseurl = "https://diapason.consulting"
title = "Diapason Consulting"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[menu]


# Main menu
[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Design and development"
    url        = "/dnd/"
    weight     = 1
    parent     = "menu.services"

[[menu.main]]
    name       = "Regulatory strategy"
    url        = "/regs/"
    weight     = 2
    parent     = "menu.services"

[[menu.main]]
    name       = "Quality systems"
    url        = "/qms/"
    weight     = 3
    parent     = "menu.services"

[[menu.main]]
    name       = "Research"
    url        = "/research/"
    weight     = 4
    parent     = "menu.services"

[[menu.main]]
    name       = "Entrepreneurship advisory"
    url        = "/advisory/"
    weight     = 5
    parent     = "menu.services"

[[menu.main]]
    name       = "Applications"
    identifier = "menu.applications"
    url        = "/" 
    weight     = 2

[[menu.main]]
    name       = "Medical Devices"
    url        = "/comingsoon/"
    weight     = 1
    parent     = "menu.applications"

[[menu.main]]
    name       = "Self tech"
    url        = "/selftech/"
    weight     = 2
    parent     = "menu.applications"

[[menu.main]]
    name       = "Digital Health"
    url        = "/comingsoon/"
    weight     = 3
    parent     = "menu.applications"
    
[[menu.main]]
    name       = "Creative Industries"
    url        =  "/creative/"
    weight     = 4
    parent     = "menu.applications"
    
[[menu.main]]
    name       = "Values"
    url        = "/values/"
    weight     = 3
 
[[menu.main]]
    name       = "About us"
    url        = "/about/"
    weight     = 4
    
[[menu.main]]
    name       = "Blog"
#    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
#    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 6
    
#[[menu.main]]
#    name       = "Resources"
#    url        = "/resources" 
#    weight     = 7


# Top bar social links menu

  
[[menu.topbar]]
    weight = 1
    name = "Linkedin"
    url = "https://www.linkedin.com/company/74754946/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/diapason-consulting"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Researchgate"
    url = "https://www.researchgate.net/profile/Pierre-Lonchampt"
    pre = "<i class='fab fa-2x fa-researchgate'></i>"
    
[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/diapasonconsult"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:pierre@diapason.consulting"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
    
[[menu.topbar]]
    weight = 6
    name = "Phone"
    url = "tel:+61 466 910 950"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Pierre Lonchampt"
    defaultKeywords = []
    mainSections = ["blog"]
    defaultDescription = "HealthTech Advisory&Consulting"

    # Social media
    # facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "diapasonconsult" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = ""

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    about_us = "Diapason Consulting		ABN 82882211500"
				
    copyright = "Copyright (c) 2022, Diapason Consulting; all rights reserved.   		 No tracking/cookie enabled:  https://gohugo.io/about/hugo-and-gdpr"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "Diapason"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Diapason Consulting</strong>
        <br>pierre@diapason.consulting
      </p>
     """

[permalinks]
    blog = "/blog/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = "Diapason Consulting"
    
# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.recent_posts]
    enable = true
    title = "From our blog"
    #subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
`

**Comment by diapason-consulting** [comment]
For point 2 thx a lot.
[config.toml.txt](https://github.com/devcows/hugo-universal-theme/files/8442795/config.toml.txt)

**Comment by diapason-consulting** [comment]
@ryanfox1985  thx a lot for the pluralisation option :)
Any idea about the blue rectangles? https://i.imgur.com/oEbWXCA.png

**Comment by ryanfox1985** [comment]
hello, sorry for the delay, the issue is with the `url`:

```toml
# Main menu
[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    url        = "/"
    weight     = 1
...
[[menu.main]]
    name       = "Applications"
    identifier = "menu.applications"
    url        = "/" 
    weight     = 2
...
```

Both have the same url to the home page.

**Comment by diapason-consulting** [comment]
Thx a lot @ryanfox1985 .
I have replaced with:

```
# Main menu
[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    url        = "/services/"
    weight     = 1

[[menu.main]]
    name       = "Applications"
    identifier = "menu.applications"
    url        = "/applications/" 
    weight     = 2
```

does not seems to change the behaviour of the blue rectangles on the home page :(

**Comment by ryanfox1985** [comment]
Hello @diapason-consulting, I could't reproduce:

![hugo_menu](https://user-images.githubusercontent.com/1152728/165032721-63b03c23-eebc-4d61-9f59-8f8a50001054.gif)

I created the values and about pages:

```bash
hugo new values.md
hugo new about.md
```

**Comment by diapason-consulting** [comment]
That's weird. It's not coming from Gitlab as it is doing the same on my local server :(
It happens only on the landing home page, i.e. when the grey top ribbon with the social links is displayed.
BTW - is this top ribbon section supposed to be there all the time? Would sound logical wouldn't it? Why having it only on the landing page ?

**Comment by diapason-consulting** [comment]
Got it thx a lot!
