### ISSUE TITLE
Is it possible to display the top bar (with the social links) on all pages?

### ISSUE THREAD

**Issue by diapason-consulting** [devcows/hugo-universal-theme#357]
As it stands now, this top bar is displayed only on the home page - not in any of the other pages or in the blog for instance.
Is there a way to change that ?

**Comment by ryanfox1985** [comment]
thanks for reporting, there was a bug on this.

**Comment by diapason-consulting** [comment]
THX  - but AFAIK it still happens: if you go on blog it disappears - and does not reappear until you come back on the home page :(

**Comment by ryanfox1985** [comment]
have you updated the theme to the latest version?

**Comment by diapason-consulting** [comment]
Recloned it - same behaviour on your demo site ?

**Comment by ryanfox1985** [comment]
I reopened the issue, I noticed in the demo page blog page is missing the header.
Other pages like contact and faq, the header is there.

**Comment by diapason-consulting** [comment]
All good thx!
Is there a better way to update the theme than to delete and reclone? (Sorry for dumb Q  -I've been using svn for decades and I'm struggling a tad with git LOL)

**Comment by diapason-consulting** [comment]
THX heaps :+1:
