### ISSUE TITLE
Date format not applied in all pages 

### ISSUE THREAD

**Issue by liponcio** [devcows/hugo-universal-theme#37]
The date format property in the config.toml file is not applied in all the pages.
For instance I configure the format to '2006-01-01' and the format applied in the pages is 'January 01, 2006'

**Comment by adrianmo** [comment]
Thanks for the heads up @liponcio. I'll take a look at it and get it fixed.

**Comment by adrianmo** [comment]
@liponcio it's now fixed. Please update the theme and check it out.
