### ISSUE TITLE
Error overriding file from template

### ISSUE THREAD

**Issue by liponcio** [devcows/hugo-universal-theme#38]
When I try to override the file layouts/_default/single.html from the theme, a Date of class "text-muted text-uppercase mb-small text-right" appears on top of all other pages.
In the blog the date is correct and appears as expected but in all other pages the date appears (when it shouldn't) an is incorrectly formated as "January 1, 0001"

**Comment by adrianmo** [comment]
@liponcio You need to override the file `layouts/page/single.html`, which is the one being used for Pages (Contact, FAQ, ...). The one that you overridden is used for individual blog posts, not pages.

Please let me know if that helps and close the issue if it worked.

Best,
-Adrian

**Comment by adrianmo** [comment]
I'm assuming that it worked as I have not received feedback in 20 days.
