### ISSUE TITLE
question: adding social icons (tiktok & bluesky)

### ISSUE THREAD

**Issue by JoshuaACasey** [devcows/hugo-universal-theme#418]
Is it possible to add social links/icons to the top bar (for example tiktok & bluesky & threads)? 

When I try to add Tiktok (`pre = "<i class='fab fa-2x fa-tiktok'></i>"`), Bluesky (`pre = "<i class='fab fa-2x fa-bluesky'></i>"`), and threads (`pre = "<i class='fab fa-2x fa-threads'></i>"`) to the config, no icon shows up. Is this not possible to add other social media platforms or am I just not doing something right

I assume it should be possible because I was successfully able to add Mastodon (`pre = "<i class='fab fa-2x fa-mastodon'></i>"`), Reddit (`pre = "<i class='fab fa-2x fa-reddit'></i>"`), and discord (`pre = "<i class='fab fa-2x fa-discord'></i>"`)

**Comment by tgouverneur** [comment]
You need to change the version that's used in `themes/hugo-universal-theme/layouts/partials/headers.html` to be 6.6.0 instead of 5.11.2.
