### ISSUE TITLE
button prev and next are always disabled

### ISSUE THREAD

**Issue by azureody2017** [devcows/hugo-universal-theme#42]
freshly cloned from github and then add 10 - 15 new item in folder blog. 
we can see that button prev and next are always disabled. 
even in http://www.devcows.com/blog we can see those two button are not functioning.
how to make those two button enable properly?

**Comment by adrianmo** [comment]
@azureody2017 I've just tested the pagination and it works fine. The "Older" button enables when the number of blog posts is greater than the pagination number (defined in the `config.toml` [here](https://github.com/devcows/hugo-universal-theme/blob/master/exampleSite/config.toml#L11)). 

Cheers,
-Adrian
