### ISSUE TITLE
Move to Fontsawesome 6

### ISSUE THREAD

**Issue by richtong** [devcows/hugo-universal-theme#421]
I don't know how alive this project is looking at the open pull requests, but its a one line change to move to font-awesome 6. I might take some of the open PRs and apply them there github.com/richtong/hugo-universal-theme if people are interested.

The docs option is really nice!

**Comment by ryanfox1985** [comment]
The version at master is already using v6.6

**Comment by richtong** [comment]
Oops. Sorry I didn't pull

Sent via Superhuman iOS ( ***@***.*** )
