### ISSUE TITLE
Center

### ISSUE THREAD

**Issue by scinfu** [devcows/hugo-universal-theme#43]
How to center the layout or divid in 3 column ?

**Comment by adrianmo** [comment]
@scinfu could you elaborate the question a bit more? I don't understand what you are trying to achieve. A sketch would be helpful too.

Thanks.

**Comment by scinfu** [comment]
@adrianmo  yes , if i make a page all text are aligned to the right of the screen . I want my page layout have 3 column , where the first and the last are empty if the screen is large.

**Comment by adrianmo** [comment]
@scinfu are you referring to blog posts and pages? You may want to override the theme's layout for the posts and pages then. Take a look at this page: https://gohugo.io/templates/blocks/

If that didn't help, please send a screenshot or sketch to help us understand it.

**Comment by scinfu** [comment]
Ok Thank you
