### ISSUE TITLE
changing order of params on homepage

### ISSUE THREAD

**Issue by liz-miller** [devcows/hugo-universal-theme#47]
I really like the different parameters that can be enabled/disabled for the home page. Is there a way to change the order that they appear in? I'd like to use the "see_more" as the first param and the "features" as the second followed by "testimonials", etc.

**Comment by schuster-rainer** [comment]
right now, just copy themes/hugo-universal-theme/layouts/index.html to layouts/index.html and edit it.

**Comment by adrianmo** [comment]
Yes, I'm closing this one. I'm happy with the proposed workaround provided by @schuster-rainer.
