### ISSUE TITLE
Display problems in Chrome on Android

### ISSUE THREAD

**Issue by LostMoho** [devcows/hugo-universal-theme#48]
This theme doesn't seem to display correctly on Chrome on an Android phone. You can try the theme's own demo:

http://themes.gohugo.io/theme/hugo-universal-theme/

The carousel and top-level menu at the least are messed up, and other things appear to be missing or scrambled.

I'm running Android 7.1.1 and Chrome 56.0.2924.87 on a Nexus 6P

**Comment by adrianmo** [comment]
@LostMoho I have already experienced the same issues in my phone. I'll dig into that and find out what's causing that...

**Comment by GeorgeWL** [comment]
@adrianmo If it's Owl Carousel causing, then we can see if there's an issue tracker for that.

I've not experienced it, if knew what you meant specifically might be able to help. (I use Firefox Nightly on mobile as it's the only one with uBlock Origin.)

How do you mean messed up? 

Can you get a screen recorder app and record it?

**Comment by adrianmo** [comment]
I'm not experiencing the issue any more. Maybe it was a problem with the gohugo.io web server, or maybe the issue was fixed as a side effect of recent update.

@LostMoho if you keep experiencing problems please reopen this issue and provide evidences to help us troubleshoot.

Thanks.
