### ISSUE TITLE
Populate .Summary with front matter

### ISSUE THREAD

**Issue by gavinwray** [devcows/hugo-universal-theme#53]
In /layouts/partials/recent_posts.html and /layouts/default/list.html, is it possible to populate:

```
<p class="intro">{{ .Summary }}</p>
```

...with a value from a post's front matter? E.g.:

```
+++
summary = "This is an excerpt summarising the post."
+++
```

**Comment by adrianmo** [comment]
Hi @gavinwray, 

By default Hugo takes the first 70 words from the post as a summary, but you can add a marker in your posts to tell Hugo where your summary ends. Please check the following site at the "User-defined: manual summary split" section: https://gohugo.io/content/summaries/

Feel free to reopen the issue if it's not resolved.
