### ISSUE TITLE
Features: md or html formatting

### ISSUE THREAD

**Issue by miranska** [devcows/hugo-universal-theme#59]
Could you please tell me, is it possible to use html or markdown language in the `description` attribute of the `features` `yaml` files? Something like:

```YAML
description: "foo *bar* baz" 
```

**Comment by adrianmo** [comment]
@miranska you can now add Markdown and HTML formatting to your features.

Cheers.

**Comment by miranska** [comment]
@adrianmo: Wow! That was fast, thanks a million!
