### ISSUE TITLE
Removal of attribution link

### ISSUE THREAD

**Issue by tdenniston** [devcows/hugo-universal-theme#72]
Hello,

Many thanks for porting this theme. 

I know there is a donation requirement from the original Bootstrapious theme for removal of the attribution link at the bottom of the page. Is there a separate requirement to support your porting work to remove the attribution link to your page?

**Comment by GeorgeWL** [comment]
I would assume yes...But with it being MIT license, not sure whether it would be to @adrianmo , @bootstrapious or to both.

**Comment by adrianmo** [comment]
Hi @tdenniston ,

You and everybody else is free to remove the porting attribution link (ie "Ported to Hugo by DevCows"). No problem at all ;)

Thanks,
-Adrian

**Comment by GeorgeWL** [comment]
What about the BootStrapious one though? there original license is CCA with the copyright link at bottom.

**Comment by adrianmo** [comment]
For the removal of the Bootstrapious attribution link you'll need to check the original theme website: https://bootstrapious.com/p/universal-business-e-commerce-template
