### ISSUE TITLE
Support for social network links in header

### ISSUE THREAD

**Issue by ringods** [devcows/hugo-universal-theme#73]
Hello,

As a business, I find it important that people can find my social handles very easy. Therefor, support for adding social network links in the header would be highly valuable. Could this support be added, using the well-known icons for each social network?

I am interested in support for:
* Github
* LinkedIn
* Twitter

To give you an idea what I'm after, have a look in the upper right corner of http://vamp.io/
You can see the Github icon as an example.

**Comment by laurentpayot** [comment]
Another example: https://monterail.com/

**Comment by GeorgeWL** [comment]
@ringods 
The whole major part of Hugo is you can just do that yourself by making a partial in layouts/partials and referencing it in the base page template.

Partials are html pages in any valid html, that are injected by hugo in the build step as if they were always in the page.

https://gohugo.io/templates/partials/

Though I do agree, it would be nice to have them pre-included.

**Comment by adrianmo** [comment]
@ringods, @GeorgeWL can you review PR #74 ? 

Thanks.

**Comment by laurentpayot** [comment]
Thanks @adrianmo 👍
