### ISSUE TITLE
Feat Request: Image responsiveness in /Content/ 

### ISSUE THREAD

**Issue by GeorgeWL** [devcows/hugo-universal-theme#78]
The current setup requires one to either create your own little shortcode which changes this for you, or to manually replace any images linked in the simple way with the html method.

It takes away some usability for those who use a headless CMS to publish content. 

I'll be honest, I've not the foggiest how to solve this.

**Comment by adrianmo** [comment]
@GeorgeWL I'm not sure what is the issue you are mentioning. Can you clarify and maybe give an example?

**Comment by GeorgeWL** [comment]
yeah, this might be just me, any images placed in the md files of content end up being placed in the site without any classes, which is fine usually, but can be a problem when a large image is placed, as it stretches out of the bounds of the div.

Putting bootstrap classes `"img img-responsive"` automagically would solve this in all cases.

@adrianmo

**Comment by adrianmo** [comment]
@GeorgeWL OK, I see what you mean now. 

Wouldn't the `figure` shortcode address this issue?

https://gohugo.io/extras/shortcodes/

```
{{< figure src="/media/cat.jpg" title="My Cat" class="img img-responsive" >}}
```

Also, you can always use plain HTML syntax instead of Markdown in content files.
```
<img src="/media/cat.jpg" class="img img-responsive" />
```

**Comment by GeorgeWL** [comment]
The problem with figure is it assumes one wants a caption,  which is often surplus to requirements.

**Comment by adrianmo** [comment]
What if you don't set the `title` attribute? Maybe it won't have caption then. I haven't tried...

**Comment by alexislg2** [comment]
I have the same problem. `figure` does not work. I had to use `<img src="/media/cat.jpg" class="img img-responsive" />` to make it work
