### ISSUE TITLE
Problems with baseurl in demo

### ISSUE THREAD

**Issue by warderm6** [devcows/hugo-universal-theme#8]
Hi Adrian,
First off, thanks for share your theme. Its a really nice theme, 
undoubtedly one of the best themes in Hugo.

Well, there is a little problem in your [demo](http://themes.gohugo.io/theme/hugo-universal-theme/). The problem is related to the baseurl used owing to the urls generated for **POST**, **FAQ** and **CONTACT** are wrong.

For example in **POST**:
The url generated at this moment is: http://themes.gohugo.io/post
when it must be: http://themes.gohugo.io/theme/hugo-universal-theme/post
This causes problems during the demo's navigation.

Solving this little problem, your theme will be more appreciated for many visitors :)

**Comment by adrianmo** [comment]
Thanks @warderm6 for the heads up and suggestions :)

I will fix it in a minute!

**Comment by adrianmo** [comment]
I fixed it in 54e5d1224ad2b463e02b267c019db02a0b68ecb6. However, it's still not updated in the Hugo themes website: http://themes.gohugo.io/theme/hugo-universal-theme/

I'll keep this issue open as a reminder until it's reflected there.

**Comment by adrianmo** [comment]
The Hugo themes showcase site has been updated and the issue is now solved! Thanks again @warderm6 👍
