### ISSUE TITLE
change "blogs" to other text

### ISSUE THREAD

**Issue by earowang** [devcows/hugo-universal-theme#88]
Hi,

Thanks for making this awesome theme. I'm just wondering how I could possibly change "blogs" to some other text in the blog index page. I poked around the `layout` folder, and couldn't find how I could make a change. Thanks a lot. 

<img width="1414" alt="screen shot 2017-06-16 at 12 12 35 pm" src="https://user-images.githubusercontent.com/2456216/27209101-3b8b4a30-528d-11e7-845b-cabad1b135f8.png">

**Comment by GeorgeWL** [comment]
Swap all mentions of the word blog(s) for the other text,  Hugo does the rest of the work on your next build.

**Comment by adrianmo** [comment]
Hi @earowang, yes, you can change the title to whatever you want without messing with the layouts.

Just add a file named `_index.md` inside `/content/blog/` with the following content:

```
+++
title = "Your new title"
+++
``` 
Please feel free to reopen the issue if you need further help.

Thanks.

**Comment by earowang** [comment]
That works perfectly. Thank you so much.

**Comment by GeorgeWL** [comment]
ha, just realised yeah my solution was like using a sledgehammer to hammer in a nail.

Sure it can do it, but it does a lot of other stuff too...derp.
