### ISSUE TITLE
Move one of the landing page segments to another page

### ISSUE THREAD

**Issue by jakegalson** [devcows/hugo-universal-theme#92]
I am trying to add the carousel segment to a different page. I thought this should be possible by creating a new directory in layouts with the name of the page, and adding a single.html file that contains {{ partial "carousel.html" . }}. It does not seem to be working - any ideas?

**Comment by GeorgeWL** [comment]
check that the partial doesn't have any express references to index page, that might be the cause.

Which make me think if it is, we should probably change it from absolute to relatives.

Do you get any errors?

Can you show us the page? Even better, can you gist the files?

**Comment by jakegalson** [comment]
As far as I can tell, there is no express reference, and I get no errors.

What I am trying to do in the long run is make a page like they have on the original bootstrapious theme that shows team members like this: http://universal.ondrejsvestka.cz/1-0/team.html. As I am new to hugo, my first step here was to attempt copying the carousel segment over to another page. Apologies for any stupid errors!

 I have put the partial carousel.html and the team/single.html file I added to the layout directory here:
https://gist.github.com/jakegalson/7cdd9fdeef08b0e023808aa8047e2fc8

**Comment by GeorgeWL** [comment]
Make a new folder in `data` for `team` and change `site.data.carousel` to `site.data.team` etc.

**Comment by jakegalson** [comment]
I just tried that, and it didn't work.

It seems to be some problem with recognising the team/single.html file. If I enter some random text in here, it does not appear in the site, so it must be using the default rather than this for some reason.

**Comment by GeorgeWL** [comment]
@jakegalson well the Hugo behaviour is if it finds an error or can't find a file,  it falls back to the defaults. 

Read through the docs quickly,  maybe you missed something?
