### ISSUE TITLE
Error while trying to build the site

### ISSUE THREAD

**Issue by wilfredgithuka** [devcows/hugo-universal-theme#97]
Error while rendering "home": template: theme/index.html:18:11: executing "theme/index.html" at <partial "carousel.ht...>: error calling partial: template: theme/partials/carousel.html:3:10: executing "theme/partials/carousel.html" at <len .Site.Data.carou...>: error calling len: len of untyped nil

**Comment by GeorgeWL** [comment]
It's stating you don't have any data in the carousel but have carousel enabled.

Either add data to `/data/carousel` or set `carousel = disable` in `config.toml`

**Comment by tbs17** [comment]
Hi, I also encounter similar issue but i don't know where to fix it. Please help!

Building sites â€¦ ERROR 2018/06/27 10:41:27 Error while rendering "home" in "": template: index.html:1:3: executing "index.html" at <partial "widget_page...>: error calling partial: template: partials/widget_page.html:23:9: executing "partials/widget_page.html" at <partial $widget $par...>: error calling partial: template: partials/widgets/posts.html:65:51: executing "partials/widgets/posts.html" at <len .Params.tags>: error calling len: len of untyped nil

**Comment by GeorgeWL** [comment]
@tbs17 sounds unrelated, open a new issue

**Comment by tbs17** [comment]
solved. Thank you!

**Comment by tbs17** [comment]
try to add tags: [xxx] in the front matter(the title section) in you .rmd
file, then you won't hit the error message like above. Let me know if it
works.

**Comment by fmerhout** [comment]
Thank you @tbs17, that did do the trick.
