### ISSUE TITLE
css issue using the theme

### ISSUE THREAD

**Issue by CLYeo** [devcows/hugo-universal-theme#98]
I'm new to hugo and is trying this beautiful theme but is unable to achieve the same outlook as the demo site using the examplesite provided

this is the result
![image](https://user-images.githubusercontent.com/29327709/28127246-7639b0e6-675e-11e7-86d4-3ebc9de91d2a.png)

looking at an older issue, someone mentioned that the demo site css is having problem with this link - http://themes.gohugo.io/theme/hugo-universal-theme/
vs the one with https
https://themes.gohugo.io/theme/hugo-universal-theme/

could it be the same issue as my local copy ?

**Comment by GeorgeWL** [comment]
I wouldn't have thought so...

Try changing the base url to the `//yourdomain.com` without using any https or https explicitly and tell me what the result is?
