### ISSUE TITLE
features

### ISSUE THREAD

**Issue by dshetty97** [devcows/hugo-universal-theme#99]
Hello! I know that this is for issues and not questions but I could not find answers to my questions and thought maybe I could try posting them here. I am sorry if this is not okay. 
I am very new to Hugo and I was wondering if there was a way to have the features on a different page other than the homepage. For example, is it possible to create a button that says "our services" on the homepage and then when someone clicks on that button they are taken to a different page where I want to use the features.
Also, it is stated that there are 4 header variations and 5 variations of the homepage. How can I look at/access those?

Thank you ^.^

**Comment by GeorgeWL** [comment]
Read the docs.

And yes. It's just plain HTML and the GO Templating Engine.

If you look in `layouts` for some of the pages you'll see something called a `partial` which looks like so
 `{{ partial "features.html" . }}` (such as in [index.html](https://github.com/devcows/hugo-universal-theme/blob/master/layouts/index.html#L20))

All a partial does is say 
>Look in the Folder inside of 'layouts' that's named  `partials`, and glue in place the contents of the file with the same name.

These partials can be put basically anywhere you want. 

And you can make your own too, if you know html and css.

I believe there are variable set in `config.toml` for the variants.
